//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/mongodb/mongodb-atlas-kubernetes/v2/api"
	common "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/common"
)

// AtlasDeploymentSpecApplyConfiguration represents a declarative configuration of the AtlasDeploymentSpec type for use
// with apply.
type AtlasDeploymentSpecApplyConfiguration struct {
	ProjectDualReferenceApplyConfiguration `json:",inline"`
	UpgradeToDedicated                     *bool                                     `json:"upgradeToDedicated,omitempty"`
	DeploymentSpec                         *AdvancedDeploymentSpecApplyConfiguration `json:"deploymentSpec,omitempty"`
	BackupScheduleRef                      *common.ResourceRefNamespaced             `json:"backupRef,omitempty"`
	ServerlessSpec                         *ServerlessSpecApplyConfiguration         `json:"serverlessSpec,omitempty"`
	ProcessArgs                            *ProcessArgsApplyConfiguration            `json:"processArgs,omitempty"`
	FlexSpec                               *FlexSpecApplyConfiguration               `json:"flexSpec,omitempty"`
}

// AtlasDeploymentSpecApplyConfiguration constructs a declarative configuration of the AtlasDeploymentSpec type for use with
// apply.
func AtlasDeploymentSpec() *AtlasDeploymentSpecApplyConfiguration {
	return &AtlasDeploymentSpecApplyConfiguration{}
}

// WithProjectRef sets the ProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectRef field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithProjectRef(value common.ResourceRefNamespaced) *AtlasDeploymentSpecApplyConfiguration {
	b.ProjectDualReferenceApplyConfiguration.ProjectRef = &value
	return b
}

// WithExternalProjectRef sets the ExternalProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalProjectRef field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithExternalProjectRef(value *ExternalProjectReferenceApplyConfiguration) *AtlasDeploymentSpecApplyConfiguration {
	b.ProjectDualReferenceApplyConfiguration.ExternalProjectRef = value
	return b
}

// WithConnectionSecret sets the ConnectionSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionSecret field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithConnectionSecret(value api.LocalObjectReference) *AtlasDeploymentSpecApplyConfiguration {
	b.ProjectDualReferenceApplyConfiguration.ConnectionSecret = &value
	return b
}

// WithUpgradeToDedicated sets the UpgradeToDedicated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpgradeToDedicated field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithUpgradeToDedicated(value bool) *AtlasDeploymentSpecApplyConfiguration {
	b.UpgradeToDedicated = &value
	return b
}

// WithDeploymentSpec sets the DeploymentSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentSpec field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithDeploymentSpec(value *AdvancedDeploymentSpecApplyConfiguration) *AtlasDeploymentSpecApplyConfiguration {
	b.DeploymentSpec = value
	return b
}

// WithBackupScheduleRef sets the BackupScheduleRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupScheduleRef field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithBackupScheduleRef(value common.ResourceRefNamespaced) *AtlasDeploymentSpecApplyConfiguration {
	b.BackupScheduleRef = &value
	return b
}

// WithServerlessSpec sets the ServerlessSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerlessSpec field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithServerlessSpec(value *ServerlessSpecApplyConfiguration) *AtlasDeploymentSpecApplyConfiguration {
	b.ServerlessSpec = value
	return b
}

// WithProcessArgs sets the ProcessArgs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessArgs field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithProcessArgs(value *ProcessArgsApplyConfiguration) *AtlasDeploymentSpecApplyConfiguration {
	b.ProcessArgs = value
	return b
}

// WithFlexSpec sets the FlexSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlexSpec field is set to the value of the last call.
func (b *AtlasDeploymentSpecApplyConfiguration) WithFlexSpec(value *FlexSpecApplyConfiguration) *AtlasDeploymentSpecApplyConfiguration {
	b.FlexSpec = value
	return b
}
