//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// AtlasStreamConnectionSpecApplyConfiguration represents a declarative configuration of the AtlasStreamConnectionSpec type for use
// with apply.
type AtlasStreamConnectionSpecApplyConfiguration struct {
	Name           *string                                    `json:"name,omitempty"`
	ConnectionType *string                                    `json:"type,omitempty"`
	ClusterConfig  *ClusterConnectionConfigApplyConfiguration `json:"clusterConfig,omitempty"`
	KafkaConfig    *StreamsKafkaConnectionApplyConfiguration  `json:"kafkaConfig,omitempty"`
}

// AtlasStreamConnectionSpecApplyConfiguration constructs a declarative configuration of the AtlasStreamConnectionSpec type for use with
// apply.
func AtlasStreamConnectionSpec() *AtlasStreamConnectionSpecApplyConfiguration {
	return &AtlasStreamConnectionSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AtlasStreamConnectionSpecApplyConfiguration) WithName(value string) *AtlasStreamConnectionSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithConnectionType sets the ConnectionType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionType field is set to the value of the last call.
func (b *AtlasStreamConnectionSpecApplyConfiguration) WithConnectionType(value string) *AtlasStreamConnectionSpecApplyConfiguration {
	b.ConnectionType = &value
	return b
}

// WithClusterConfig sets the ClusterConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterConfig field is set to the value of the last call.
func (b *AtlasStreamConnectionSpecApplyConfiguration) WithClusterConfig(value *ClusterConnectionConfigApplyConfiguration) *AtlasStreamConnectionSpecApplyConfiguration {
	b.ClusterConfig = value
	return b
}

// WithKafkaConfig sets the KafkaConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KafkaConfig field is set to the value of the last call.
func (b *AtlasStreamConnectionSpecApplyConfiguration) WithKafkaConfig(value *StreamsKafkaConnectionApplyConfiguration) *AtlasStreamConnectionSpecApplyConfiguration {
	b.KafkaConfig = value
	return b
}
