//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// AtlasSearchIndexAnalyzerApplyConfiguration represents a declarative configuration of the AtlasSearchIndexAnalyzer type for use
// with apply.
type AtlasSearchIndexAnalyzerApplyConfiguration struct {
	Name         *string                      `json:"name,omitempty"`
	TokenFilters *apiextensionsv1.JSON        `json:"tokenFilters,omitempty"`
	CharFilters  *apiextensionsv1.JSON        `json:"charFilters,omitempty"`
	Tokenizer    *TokenizerApplyConfiguration `json:"tokenizer,omitempty"`
}

// AtlasSearchIndexAnalyzerApplyConfiguration constructs a declarative configuration of the AtlasSearchIndexAnalyzer type for use with
// apply.
func AtlasSearchIndexAnalyzer() *AtlasSearchIndexAnalyzerApplyConfiguration {
	return &AtlasSearchIndexAnalyzerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AtlasSearchIndexAnalyzerApplyConfiguration) WithName(value string) *AtlasSearchIndexAnalyzerApplyConfiguration {
	b.Name = &value
	return b
}

// WithTokenFilters sets the TokenFilters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenFilters field is set to the value of the last call.
func (b *AtlasSearchIndexAnalyzerApplyConfiguration) WithTokenFilters(value apiextensionsv1.JSON) *AtlasSearchIndexAnalyzerApplyConfiguration {
	b.TokenFilters = &value
	return b
}

// WithCharFilters sets the CharFilters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CharFilters field is set to the value of the last call.
func (b *AtlasSearchIndexAnalyzerApplyConfiguration) WithCharFilters(value apiextensionsv1.JSON) *AtlasSearchIndexAnalyzerApplyConfiguration {
	b.CharFilters = &value
	return b
}

// WithTokenizer sets the Tokenizer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tokenizer field is set to the value of the last call.
func (b *AtlasSearchIndexAnalyzerApplyConfiguration) WithTokenizer(value *TokenizerApplyConfiguration) *AtlasSearchIndexAnalyzerApplyConfiguration {
	b.Tokenizer = value
	return b
}
