//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	common "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/common"
)

// AtlasFederatedAuthSpecApplyConfiguration represents a declarative configuration of the AtlasFederatedAuthSpec type for use
// with apply.
type AtlasFederatedAuthSpecApplyConfiguration struct {
	Enabled                     *bool                           `json:"enabled,omitempty"`
	ConnectionSecretRef         *common.ResourceRefNamespaced   `json:"connectionSecretRef,omitempty"`
	DomainAllowList             []string                        `json:"domainAllowList,omitempty"`
	DomainRestrictionEnabled    *bool                           `json:"domainRestrictionEnabled,omitempty"`
	SSODebugEnabled             *bool                           `json:"ssoDebugEnabled,omitempty"`
	PostAuthRoleGrants          []string                        `json:"postAuthRoleGrants,omitempty"`
	RoleMappings                []RoleMappingApplyConfiguration `json:"roleMappings,omitempty"`
	DataAccessIdentityProviders *[]string                       `json:"dataAccessIdentityProviders,omitempty"`
}

// AtlasFederatedAuthSpecApplyConfiguration constructs a declarative configuration of the AtlasFederatedAuthSpec type for use with
// apply.
func AtlasFederatedAuthSpec() *AtlasFederatedAuthSpecApplyConfiguration {
	return &AtlasFederatedAuthSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AtlasFederatedAuthSpecApplyConfiguration) WithEnabled(value bool) *AtlasFederatedAuthSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithConnectionSecretRef sets the ConnectionSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionSecretRef field is set to the value of the last call.
func (b *AtlasFederatedAuthSpecApplyConfiguration) WithConnectionSecretRef(value common.ResourceRefNamespaced) *AtlasFederatedAuthSpecApplyConfiguration {
	b.ConnectionSecretRef = &value
	return b
}

// WithDomainAllowList adds the given value to the DomainAllowList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DomainAllowList field.
func (b *AtlasFederatedAuthSpecApplyConfiguration) WithDomainAllowList(values ...string) *AtlasFederatedAuthSpecApplyConfiguration {
	for i := range values {
		b.DomainAllowList = append(b.DomainAllowList, values[i])
	}
	return b
}

// WithDomainRestrictionEnabled sets the DomainRestrictionEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainRestrictionEnabled field is set to the value of the last call.
func (b *AtlasFederatedAuthSpecApplyConfiguration) WithDomainRestrictionEnabled(value bool) *AtlasFederatedAuthSpecApplyConfiguration {
	b.DomainRestrictionEnabled = &value
	return b
}

// WithSSODebugEnabled sets the SSODebugEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSODebugEnabled field is set to the value of the last call.
func (b *AtlasFederatedAuthSpecApplyConfiguration) WithSSODebugEnabled(value bool) *AtlasFederatedAuthSpecApplyConfiguration {
	b.SSODebugEnabled = &value
	return b
}

// WithPostAuthRoleGrants adds the given value to the PostAuthRoleGrants field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PostAuthRoleGrants field.
func (b *AtlasFederatedAuthSpecApplyConfiguration) WithPostAuthRoleGrants(values ...string) *AtlasFederatedAuthSpecApplyConfiguration {
	for i := range values {
		b.PostAuthRoleGrants = append(b.PostAuthRoleGrants, values[i])
	}
	return b
}

// WithRoleMappings adds the given value to the RoleMappings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RoleMappings field.
func (b *AtlasFederatedAuthSpecApplyConfiguration) WithRoleMappings(values ...*RoleMappingApplyConfiguration) *AtlasFederatedAuthSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoleMappings")
		}
		b.RoleMappings = append(b.RoleMappings, *values[i])
	}
	return b
}

// WithDataAccessIdentityProviders sets the DataAccessIdentityProviders field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataAccessIdentityProviders field is set to the value of the last call.
func (b *AtlasFederatedAuthSpecApplyConfiguration) WithDataAccessIdentityProviders(value []string) *AtlasFederatedAuthSpecApplyConfiguration {
	b.DataAccessIdentityProviders = &value
	return b
}
