//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	common "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/common"
)

// AtlasBackupScheduleSpecApplyConfiguration represents a declarative configuration of the AtlasBackupScheduleSpec type for use
// with apply.
type AtlasBackupScheduleSpecApplyConfiguration struct {
	AutoExportEnabled                 *bool                                    `json:"autoExportEnabled,omitempty"`
	Export                            *AtlasBackupExportSpecApplyConfiguration `json:"export,omitempty"`
	PolicyRef                         *common.ResourceRefNamespaced            `json:"policy,omitempty"`
	ReferenceHourOfDay                *int64                                   `json:"referenceHourOfDay,omitempty"`
	ReferenceMinuteOfHour             *int64                                   `json:"referenceMinuteOfHour,omitempty"`
	RestoreWindowDays                 *int64                                   `json:"restoreWindowDays,omitempty"`
	UpdateSnapshots                   *bool                                    `json:"updateSnapshots,omitempty"`
	UseOrgAndGroupNamesInExportPrefix *bool                                    `json:"useOrgAndGroupNamesInExportPrefix,omitempty"`
	CopySettings                      []CopySettingApplyConfiguration          `json:"copySettings,omitempty"`
}

// AtlasBackupScheduleSpecApplyConfiguration constructs a declarative configuration of the AtlasBackupScheduleSpec type for use with
// apply.
func AtlasBackupScheduleSpec() *AtlasBackupScheduleSpecApplyConfiguration {
	return &AtlasBackupScheduleSpecApplyConfiguration{}
}

// WithAutoExportEnabled sets the AutoExportEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoExportEnabled field is set to the value of the last call.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithAutoExportEnabled(value bool) *AtlasBackupScheduleSpecApplyConfiguration {
	b.AutoExportEnabled = &value
	return b
}

// WithExport sets the Export field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Export field is set to the value of the last call.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithExport(value *AtlasBackupExportSpecApplyConfiguration) *AtlasBackupScheduleSpecApplyConfiguration {
	b.Export = value
	return b
}

// WithPolicyRef sets the PolicyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicyRef field is set to the value of the last call.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithPolicyRef(value common.ResourceRefNamespaced) *AtlasBackupScheduleSpecApplyConfiguration {
	b.PolicyRef = &value
	return b
}

// WithReferenceHourOfDay sets the ReferenceHourOfDay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReferenceHourOfDay field is set to the value of the last call.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithReferenceHourOfDay(value int64) *AtlasBackupScheduleSpecApplyConfiguration {
	b.ReferenceHourOfDay = &value
	return b
}

// WithReferenceMinuteOfHour sets the ReferenceMinuteOfHour field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReferenceMinuteOfHour field is set to the value of the last call.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithReferenceMinuteOfHour(value int64) *AtlasBackupScheduleSpecApplyConfiguration {
	b.ReferenceMinuteOfHour = &value
	return b
}

// WithRestoreWindowDays sets the RestoreWindowDays field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestoreWindowDays field is set to the value of the last call.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithRestoreWindowDays(value int64) *AtlasBackupScheduleSpecApplyConfiguration {
	b.RestoreWindowDays = &value
	return b
}

// WithUpdateSnapshots sets the UpdateSnapshots field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateSnapshots field is set to the value of the last call.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithUpdateSnapshots(value bool) *AtlasBackupScheduleSpecApplyConfiguration {
	b.UpdateSnapshots = &value
	return b
}

// WithUseOrgAndGroupNamesInExportPrefix sets the UseOrgAndGroupNamesInExportPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseOrgAndGroupNamesInExportPrefix field is set to the value of the last call.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithUseOrgAndGroupNamesInExportPrefix(value bool) *AtlasBackupScheduleSpecApplyConfiguration {
	b.UseOrgAndGroupNamesInExportPrefix = &value
	return b
}

// WithCopySettings adds the given value to the CopySettings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CopySettings field.
func (b *AtlasBackupScheduleSpecApplyConfiguration) WithCopySettings(values ...*CopySettingApplyConfiguration) *AtlasBackupScheduleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCopySettings")
		}
		b.CopySettings = append(b.CopySettings, *values[i])
	}
	return b
}
