//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	common "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/common"
)

// AtlasStreamInstanceSpecApplyConfiguration represents a declarative configuration of the AtlasStreamInstanceSpec type for use
// with apply.
type AtlasStreamInstanceSpecApplyConfiguration struct {
	Name               *string                        `json:"name,omitempty"`
	Config             *ConfigApplyConfiguration      `json:"clusterConfig,omitempty"`
	Project            *common.ResourceRefNamespaced  `json:"projectRef,omitempty"`
	ConnectionRegistry []common.ResourceRefNamespaced `json:"connectionRegistry,omitempty"`
}

// AtlasStreamInstanceSpecApplyConfiguration constructs a declarative configuration of the AtlasStreamInstanceSpec type for use with
// apply.
func AtlasStreamInstanceSpec() *AtlasStreamInstanceSpecApplyConfiguration {
	return &AtlasStreamInstanceSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AtlasStreamInstanceSpecApplyConfiguration) WithName(value string) *AtlasStreamInstanceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *AtlasStreamInstanceSpecApplyConfiguration) WithConfig(value *ConfigApplyConfiguration) *AtlasStreamInstanceSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithProject sets the Project field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Project field is set to the value of the last call.
func (b *AtlasStreamInstanceSpecApplyConfiguration) WithProject(value common.ResourceRefNamespaced) *AtlasStreamInstanceSpecApplyConfiguration {
	b.Project = &value
	return b
}

// WithConnectionRegistry adds the given value to the ConnectionRegistry field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ConnectionRegistry field.
func (b *AtlasStreamInstanceSpecApplyConfiguration) WithConnectionRegistry(values ...common.ResourceRefNamespaced) *AtlasStreamInstanceSpecApplyConfiguration {
	for i := range values {
		b.ConnectionRegistry = append(b.ConnectionRegistry, values[i])
	}
	return b
}
