//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/mongodb/mongodb-atlas-kubernetes/v2/api"
	common "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/common"
)

// AtlasThirdPartyIntegrationSpecApplyConfiguration represents a declarative configuration of the AtlasThirdPartyIntegrationSpec type for use
// with apply.
type AtlasThirdPartyIntegrationSpecApplyConfiguration struct {
	ProjectDualReferenceApplyConfiguration `json:",inline"`
	Type                                   *string                                      `json:"type,omitempty"`
	Datadog                                *DatadogIntegrationApplyConfiguration        `json:"datadog,omitempty"`
	MicrosoftTeams                         *MicrosoftTeamsIntegrationApplyConfiguration `json:"microsoftTeams,omitempty"`
	NewRelic                               *NewRelicIntegrationApplyConfiguration       `json:"newRelic,omitempty"`
	OpsGenie                               *OpsGenieIntegrationApplyConfiguration       `json:"opsGenie,omitempty"`
	PagerDuty                              *PagerDutyIntegrationApplyConfiguration      `json:"pagerDuty,omitempty"`
	Prometheus                             *PrometheusIntegrationApplyConfiguration     `json:"prometheus,omitempty"`
	Slack                                  *SlackIntegrationApplyConfiguration          `json:"slack,omitempty"`
	VictorOps                              *VictorOpsIntegrationApplyConfiguration      `json:"victorOps,omitempty"`
	Webhook                                *WebhookIntegrationApplyConfiguration        `json:"webhook,omitempty"`
}

// AtlasThirdPartyIntegrationSpecApplyConfiguration constructs a declarative configuration of the AtlasThirdPartyIntegrationSpec type for use with
// apply.
func AtlasThirdPartyIntegrationSpec() *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	return &AtlasThirdPartyIntegrationSpecApplyConfiguration{}
}

// WithProjectRef sets the ProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectRef field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithProjectRef(value common.ResourceRefNamespaced) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.ProjectDualReferenceApplyConfiguration.ProjectRef = &value
	return b
}

// WithExternalProjectRef sets the ExternalProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalProjectRef field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithExternalProjectRef(value *ExternalProjectReferenceApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.ProjectDualReferenceApplyConfiguration.ExternalProjectRef = value
	return b
}

// WithConnectionSecret sets the ConnectionSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionSecret field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithConnectionSecret(value api.LocalObjectReference) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.ProjectDualReferenceApplyConfiguration.ConnectionSecret = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithType(value string) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithDatadog sets the Datadog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Datadog field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithDatadog(value *DatadogIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.Datadog = value
	return b
}

// WithMicrosoftTeams sets the MicrosoftTeams field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MicrosoftTeams field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithMicrosoftTeams(value *MicrosoftTeamsIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.MicrosoftTeams = value
	return b
}

// WithNewRelic sets the NewRelic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NewRelic field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithNewRelic(value *NewRelicIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.NewRelic = value
	return b
}

// WithOpsGenie sets the OpsGenie field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpsGenie field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithOpsGenie(value *OpsGenieIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.OpsGenie = value
	return b
}

// WithPagerDuty sets the PagerDuty field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PagerDuty field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithPagerDuty(value *PagerDutyIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.PagerDuty = value
	return b
}

// WithPrometheus sets the Prometheus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prometheus field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithPrometheus(value *PrometheusIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.Prometheus = value
	return b
}

// WithSlack sets the Slack field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Slack field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithSlack(value *SlackIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.Slack = value
	return b
}

// WithVictorOps sets the VictorOps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VictorOps field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithVictorOps(value *VictorOpsIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.VictorOps = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *AtlasThirdPartyIntegrationSpecApplyConfiguration) WithWebhook(value *WebhookIntegrationApplyConfiguration) *AtlasThirdPartyIntegrationSpecApplyConfiguration {
	b.Webhook = value
	return b
}
