//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// AuditingApplyConfiguration represents a declarative configuration of the Auditing type for use
// with apply.
type AuditingApplyConfiguration struct {
	AuditAuthorizationSuccess *bool   `json:"auditAuthorizationSuccess,omitempty"`
	AuditFilter               *string `json:"auditFilter,omitempty"`
	Enabled                   *bool   `json:"enabled,omitempty"`
}

// AuditingApplyConfiguration constructs a declarative configuration of the Auditing type for use with
// apply.
func Auditing() *AuditingApplyConfiguration {
	return &AuditingApplyConfiguration{}
}

// WithAuditAuthorizationSuccess sets the AuditAuthorizationSuccess field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuditAuthorizationSuccess field is set to the value of the last call.
func (b *AuditingApplyConfiguration) WithAuditAuthorizationSuccess(value bool) *AuditingApplyConfiguration {
	b.AuditAuthorizationSuccess = &value
	return b
}

// WithAuditFilter sets the AuditFilter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuditFilter field is set to the value of the last call.
func (b *AuditingApplyConfiguration) WithAuditFilter(value string) *AuditingApplyConfiguration {
	b.AuditFilter = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AuditingApplyConfiguration) WithEnabled(value bool) *AuditingApplyConfiguration {
	b.Enabled = &value
	return b
}
