//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// AzurePrivateEndpointConfigurationApplyConfiguration represents a declarative configuration of the AzurePrivateEndpointConfiguration type for use
// with apply.
type AzurePrivateEndpointConfigurationApplyConfiguration struct {
	ID *string `json:"id,omitempty"`
	IP *string `json:"ipAddress,omitempty"`
}

// AzurePrivateEndpointConfigurationApplyConfiguration constructs a declarative configuration of the AzurePrivateEndpointConfiguration type for use with
// apply.
func AzurePrivateEndpointConfiguration() *AzurePrivateEndpointConfigurationApplyConfiguration {
	return &AzurePrivateEndpointConfigurationApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *AzurePrivateEndpointConfigurationApplyConfiguration) WithID(value string) *AzurePrivateEndpointConfigurationApplyConfiguration {
	b.ID = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *AzurePrivateEndpointConfigurationApplyConfiguration) WithIP(value string) *AzurePrivateEndpointConfigurationApplyConfiguration {
	b.IP = &value
	return b
}
