//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// ConfigApplyConfiguration represents a declarative configuration of the Config type for use
// with apply.
type ConfigApplyConfiguration struct {
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
	Tier     *string `json:"tier,omitempty"`
}

// ConfigApplyConfiguration constructs a declarative configuration of the Config type for use with
// apply.
func Config() *ConfigApplyConfiguration {
	return &ConfigApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *ConfigApplyConfiguration) WithProvider(value string) *ConfigApplyConfiguration {
	b.Provider = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *ConfigApplyConfiguration) WithRegion(value string) *ConfigApplyConfiguration {
	b.Region = &value
	return b
}

// WithTier sets the Tier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tier field is set to the value of the last call.
func (b *ConfigApplyConfiguration) WithTier(value string) *ConfigApplyConfiguration {
	b.Tier = &value
	return b
}
