//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// CopySettingApplyConfiguration represents a declarative configuration of the CopySetting type for use
// with apply.
type CopySettingApplyConfiguration struct {
	CloudProvider    *string  `json:"cloudProvider,omitempty"`
	RegionName       *string  `json:"regionName,omitempty"`
	ShouldCopyOplogs *bool    `json:"shouldCopyOplogs,omitempty"`
	Frequencies      []string `json:"frequencies,omitempty"`
}

// CopySettingApplyConfiguration constructs a declarative configuration of the CopySetting type for use with
// apply.
func CopySetting() *CopySettingApplyConfiguration {
	return &CopySettingApplyConfiguration{}
}

// WithCloudProvider sets the CloudProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudProvider field is set to the value of the last call.
func (b *CopySettingApplyConfiguration) WithCloudProvider(value string) *CopySettingApplyConfiguration {
	b.CloudProvider = &value
	return b
}

// WithRegionName sets the RegionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RegionName field is set to the value of the last call.
func (b *CopySettingApplyConfiguration) WithRegionName(value string) *CopySettingApplyConfiguration {
	b.RegionName = &value
	return b
}

// WithShouldCopyOplogs sets the ShouldCopyOplogs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShouldCopyOplogs field is set to the value of the last call.
func (b *CopySettingApplyConfiguration) WithShouldCopyOplogs(value bool) *CopySettingApplyConfiguration {
	b.ShouldCopyOplogs = &value
	return b
}

// WithFrequencies adds the given value to the Frequencies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Frequencies field.
func (b *CopySettingApplyConfiguration) WithFrequencies(values ...string) *CopySettingApplyConfiguration {
	for i := range values {
		b.Frequencies = append(b.Frequencies, values[i])
	}
	return b
}
