//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// DatabaseApplyConfiguration represents a declarative configuration of the Database type for use
// with apply.
type DatabaseApplyConfiguration struct {
	Collections            []CollectionApplyConfiguration `json:"collections,omitempty"`
	MaxWildcardCollections *int                           `json:"maxWildcardCollections,omitempty"`
	Name                   *string                        `json:"name,omitempty"`
	Views                  []ViewApplyConfiguration       `json:"views,omitempty"`
}

// DatabaseApplyConfiguration constructs a declarative configuration of the Database type for use with
// apply.
func Database() *DatabaseApplyConfiguration {
	return &DatabaseApplyConfiguration{}
}

// WithCollections adds the given value to the Collections field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Collections field.
func (b *DatabaseApplyConfiguration) WithCollections(values ...*CollectionApplyConfiguration) *DatabaseApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCollections")
		}
		b.Collections = append(b.Collections, *values[i])
	}
	return b
}

// WithMaxWildcardCollections sets the MaxWildcardCollections field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxWildcardCollections field is set to the value of the last call.
func (b *DatabaseApplyConfiguration) WithMaxWildcardCollections(value int) *DatabaseApplyConfiguration {
	b.MaxWildcardCollections = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DatabaseApplyConfiguration) WithName(value string) *DatabaseApplyConfiguration {
	b.Name = &value
	return b
}

// WithViews adds the given value to the Views field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Views field.
func (b *DatabaseApplyConfiguration) WithViews(values ...*ViewApplyConfiguration) *DatabaseApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithViews")
		}
		b.Views = append(b.Views, *values[i])
	}
	return b
}
