//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// DataProcessRegionApplyConfiguration represents a declarative configuration of the DataProcessRegion type for use
// with apply.
type DataProcessRegionApplyConfiguration struct {
	CloudProvider *string `json:"cloudProvider,omitempty"`
	Region        *string `json:"region,omitempty"`
}

// DataProcessRegionApplyConfiguration constructs a declarative configuration of the DataProcessRegion type for use with
// apply.
func DataProcessRegion() *DataProcessRegionApplyConfiguration {
	return &DataProcessRegionApplyConfiguration{}
}

// WithCloudProvider sets the CloudProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudProvider field is set to the value of the last call.
func (b *DataProcessRegionApplyConfiguration) WithCloudProvider(value string) *DataProcessRegionApplyConfiguration {
	b.CloudProvider = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *DataProcessRegionApplyConfiguration) WithRegion(value string) *DataProcessRegionApplyConfiguration {
	b.Region = &value
	return b
}
