//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1"
)

// FlexSpecApplyConfiguration represents a declarative configuration of the FlexSpec type for use
// with apply.
type FlexSpecApplyConfiguration struct {
	Name                         *string                                 `json:"name,omitempty"`
	Tags                         []*apiv1.TagSpec                        `json:"tags,omitempty"`
	TerminationProtectionEnabled *bool                                   `json:"terminationProtectionEnabled,omitempty"`
	ProviderSettings             *FlexProviderSettingsApplyConfiguration `json:"providerSettings,omitempty"`
}

// FlexSpecApplyConfiguration constructs a declarative configuration of the FlexSpec type for use with
// apply.
func FlexSpec() *FlexSpecApplyConfiguration {
	return &FlexSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *FlexSpecApplyConfiguration) WithName(value string) *FlexSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *FlexSpecApplyConfiguration) WithTags(values ...**apiv1.TagSpec) *FlexSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTags")
		}
		b.Tags = append(b.Tags, *values[i])
	}
	return b
}

// WithTerminationProtectionEnabled sets the TerminationProtectionEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminationProtectionEnabled field is set to the value of the last call.
func (b *FlexSpecApplyConfiguration) WithTerminationProtectionEnabled(value bool) *FlexSpecApplyConfiguration {
	b.TerminationProtectionEnabled = &value
	return b
}

// WithProviderSettings sets the ProviderSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderSettings field is set to the value of the last call.
func (b *FlexSpecApplyConfiguration) WithProviderSettings(value *FlexProviderSettingsApplyConfiguration) *FlexSpecApplyConfiguration {
	b.ProviderSettings = value
	return b
}
