//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	provider "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/provider"
)

// NetworkPeerApplyConfiguration represents a declarative configuration of the NetworkPeer type for use
// with apply.
type NetworkPeerApplyConfiguration struct {
	AccepterRegionName  *string                `json:"accepterRegionName,omitempty"`
	ContainerRegion     *string                `json:"containerRegion,omitempty"`
	AWSAccountID        *string                `json:"awsAccountId,omitempty"`
	ContainerID         *string                `json:"containerId,omitempty"`
	ProviderName        *provider.ProviderName `json:"providerName,omitempty"`
	RouteTableCIDRBlock *string                `json:"routeTableCidrBlock,omitempty"`
	VpcID               *string                `json:"vpcId,omitempty"`
	AtlasCIDRBlock      *string                `json:"atlasCidrBlock,omitempty"`
	AzureDirectoryID    *string                `json:"azureDirectoryId,omitempty"`
	AzureSubscriptionID *string                `json:"azureSubscriptionId,omitempty"`
	ResourceGroupName   *string                `json:"resourceGroupName,omitempty"`
	VNetName            *string                `json:"vnetName,omitempty"`
	GCPProjectID        *string                `json:"gcpProjectId,omitempty"`
	NetworkName         *string                `json:"networkName,omitempty"`
}

// NetworkPeerApplyConfiguration constructs a declarative configuration of the NetworkPeer type for use with
// apply.
func NetworkPeer() *NetworkPeerApplyConfiguration {
	return &NetworkPeerApplyConfiguration{}
}

// WithAccepterRegionName sets the AccepterRegionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccepterRegionName field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithAccepterRegionName(value string) *NetworkPeerApplyConfiguration {
	b.AccepterRegionName = &value
	return b
}

// WithContainerRegion sets the ContainerRegion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerRegion field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithContainerRegion(value string) *NetworkPeerApplyConfiguration {
	b.ContainerRegion = &value
	return b
}

// WithAWSAccountID sets the AWSAccountID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AWSAccountID field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithAWSAccountID(value string) *NetworkPeerApplyConfiguration {
	b.AWSAccountID = &value
	return b
}

// WithContainerID sets the ContainerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerID field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithContainerID(value string) *NetworkPeerApplyConfiguration {
	b.ContainerID = &value
	return b
}

// WithProviderName sets the ProviderName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderName field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithProviderName(value provider.ProviderName) *NetworkPeerApplyConfiguration {
	b.ProviderName = &value
	return b
}

// WithRouteTableCIDRBlock sets the RouteTableCIDRBlock field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouteTableCIDRBlock field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithRouteTableCIDRBlock(value string) *NetworkPeerApplyConfiguration {
	b.RouteTableCIDRBlock = &value
	return b
}

// WithVpcID sets the VpcID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VpcID field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithVpcID(value string) *NetworkPeerApplyConfiguration {
	b.VpcID = &value
	return b
}

// WithAtlasCIDRBlock sets the AtlasCIDRBlock field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AtlasCIDRBlock field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithAtlasCIDRBlock(value string) *NetworkPeerApplyConfiguration {
	b.AtlasCIDRBlock = &value
	return b
}

// WithAzureDirectoryID sets the AzureDirectoryID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AzureDirectoryID field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithAzureDirectoryID(value string) *NetworkPeerApplyConfiguration {
	b.AzureDirectoryID = &value
	return b
}

// WithAzureSubscriptionID sets the AzureSubscriptionID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AzureSubscriptionID field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithAzureSubscriptionID(value string) *NetworkPeerApplyConfiguration {
	b.AzureSubscriptionID = &value
	return b
}

// WithResourceGroupName sets the ResourceGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceGroupName field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithResourceGroupName(value string) *NetworkPeerApplyConfiguration {
	b.ResourceGroupName = &value
	return b
}

// WithVNetName sets the VNetName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VNetName field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithVNetName(value string) *NetworkPeerApplyConfiguration {
	b.VNetName = &value
	return b
}

// WithGCPProjectID sets the GCPProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GCPProjectID field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithGCPProjectID(value string) *NetworkPeerApplyConfiguration {
	b.GCPProjectID = &value
	return b
}

// WithNetworkName sets the NetworkName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkName field is set to the value of the last call.
func (b *NetworkPeerApplyConfiguration) WithNetworkName(value string) *NetworkPeerApplyConfiguration {
	b.NetworkName = &value
	return b
}
