//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	common "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/common"
)

// NotificationApplyConfiguration represents a declarative configuration of the Notification type for use
// with apply.
type NotificationApplyConfiguration struct {
	APITokenRef         *common.ResourceRefNamespaced `json:"apiTokenRef,omitempty"`
	ChannelName         *string                       `json:"channelName,omitempty"`
	DatadogAPIKeyRef    *common.ResourceRefNamespaced `json:"datadogAPIKeyRef,omitempty"`
	DatadogRegion       *string                       `json:"datadogRegion,omitempty"`
	DelayMin            *int                          `json:"delayMin,omitempty"`
	EmailAddress        *string                       `json:"emailAddress,omitempty"`
	EmailEnabled        *bool                         `json:"emailEnabled,omitempty"`
	FlowdockAPITokenRef *common.ResourceRefNamespaced `json:"flowdockApiTokenRef,omitempty"`
	FlowName            *string                       `json:"flowName,omitempty"`
	IntervalMin         *int                          `json:"intervalMin,omitempty"`
	MobileNumber        *string                       `json:"mobileNumber,omitempty"`
	OpsGenieAPIKeyRef   *common.ResourceRefNamespaced `json:"opsGenieApiKeyRef,omitempty"`
	OpsGenieRegion      *string                       `json:"opsGenieRegion,omitempty"`
	OrgName             *string                       `json:"orgName,omitempty"`
	ServiceKeyRef       *common.ResourceRefNamespaced `json:"serviceKeyRef,omitempty"`
	SMSEnabled          *bool                         `json:"smsEnabled,omitempty"`
	TeamID              *string                       `json:"teamId,omitempty"`
	TeamName            *string                       `json:"teamName,omitempty"`
	TypeName            *string                       `json:"typeName,omitempty"`
	Username            *string                       `json:"username,omitempty"`
	VictorOpsSecretRef  *common.ResourceRefNamespaced `json:"victorOpsSecretRef,omitempty"`
	Roles               []string                      `json:"roles,omitempty"`
}

// NotificationApplyConfiguration constructs a declarative configuration of the Notification type for use with
// apply.
func Notification() *NotificationApplyConfiguration {
	return &NotificationApplyConfiguration{}
}

// WithAPITokenRef sets the APITokenRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APITokenRef field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithAPITokenRef(value common.ResourceRefNamespaced) *NotificationApplyConfiguration {
	b.APITokenRef = &value
	return b
}

// WithChannelName sets the ChannelName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChannelName field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithChannelName(value string) *NotificationApplyConfiguration {
	b.ChannelName = &value
	return b
}

// WithDatadogAPIKeyRef sets the DatadogAPIKeyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DatadogAPIKeyRef field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithDatadogAPIKeyRef(value common.ResourceRefNamespaced) *NotificationApplyConfiguration {
	b.DatadogAPIKeyRef = &value
	return b
}

// WithDatadogRegion sets the DatadogRegion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DatadogRegion field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithDatadogRegion(value string) *NotificationApplyConfiguration {
	b.DatadogRegion = &value
	return b
}

// WithDelayMin sets the DelayMin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DelayMin field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithDelayMin(value int) *NotificationApplyConfiguration {
	b.DelayMin = &value
	return b
}

// WithEmailAddress sets the EmailAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmailAddress field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithEmailAddress(value string) *NotificationApplyConfiguration {
	b.EmailAddress = &value
	return b
}

// WithEmailEnabled sets the EmailEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmailEnabled field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithEmailEnabled(value bool) *NotificationApplyConfiguration {
	b.EmailEnabled = &value
	return b
}

// WithFlowdockAPITokenRef sets the FlowdockAPITokenRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlowdockAPITokenRef field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithFlowdockAPITokenRef(value common.ResourceRefNamespaced) *NotificationApplyConfiguration {
	b.FlowdockAPITokenRef = &value
	return b
}

// WithFlowName sets the FlowName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlowName field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithFlowName(value string) *NotificationApplyConfiguration {
	b.FlowName = &value
	return b
}

// WithIntervalMin sets the IntervalMin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IntervalMin field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithIntervalMin(value int) *NotificationApplyConfiguration {
	b.IntervalMin = &value
	return b
}

// WithMobileNumber sets the MobileNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MobileNumber field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithMobileNumber(value string) *NotificationApplyConfiguration {
	b.MobileNumber = &value
	return b
}

// WithOpsGenieAPIKeyRef sets the OpsGenieAPIKeyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpsGenieAPIKeyRef field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithOpsGenieAPIKeyRef(value common.ResourceRefNamespaced) *NotificationApplyConfiguration {
	b.OpsGenieAPIKeyRef = &value
	return b
}

// WithOpsGenieRegion sets the OpsGenieRegion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpsGenieRegion field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithOpsGenieRegion(value string) *NotificationApplyConfiguration {
	b.OpsGenieRegion = &value
	return b
}

// WithOrgName sets the OrgName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OrgName field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithOrgName(value string) *NotificationApplyConfiguration {
	b.OrgName = &value
	return b
}

// WithServiceKeyRef sets the ServiceKeyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceKeyRef field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithServiceKeyRef(value common.ResourceRefNamespaced) *NotificationApplyConfiguration {
	b.ServiceKeyRef = &value
	return b
}

// WithSMSEnabled sets the SMSEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SMSEnabled field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithSMSEnabled(value bool) *NotificationApplyConfiguration {
	b.SMSEnabled = &value
	return b
}

// WithTeamID sets the TeamID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TeamID field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithTeamID(value string) *NotificationApplyConfiguration {
	b.TeamID = &value
	return b
}

// WithTeamName sets the TeamName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TeamName field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithTeamName(value string) *NotificationApplyConfiguration {
	b.TeamName = &value
	return b
}

// WithTypeName sets the TypeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TypeName field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithTypeName(value string) *NotificationApplyConfiguration {
	b.TypeName = &value
	return b
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithUsername(value string) *NotificationApplyConfiguration {
	b.Username = &value
	return b
}

// WithVictorOpsSecretRef sets the VictorOpsSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VictorOpsSecretRef field is set to the value of the last call.
func (b *NotificationApplyConfiguration) WithVictorOpsSecretRef(value common.ResourceRefNamespaced) *NotificationApplyConfiguration {
	b.VictorOpsSecretRef = &value
	return b
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *NotificationApplyConfiguration) WithRoles(values ...string) *NotificationApplyConfiguration {
	for i := range values {
		b.Roles = append(b.Roles, values[i])
	}
	return b
}
