//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// ProcessArgsApplyConfiguration represents a declarative configuration of the ProcessArgs type for use
// with apply.
type ProcessArgsApplyConfiguration struct {
	DefaultReadConcern               *string `json:"defaultReadConcern,omitempty"`
	DefaultWriteConcern              *string `json:"defaultWriteConcern,omitempty"`
	MinimumEnabledTLSProtocol        *string `json:"minimumEnabledTlsProtocol,omitempty"`
	FailIndexKeyTooLong              *bool   `json:"failIndexKeyTooLong,omitempty"`
	JavascriptEnabled                *bool   `json:"javascriptEnabled,omitempty"`
	NoTableScan                      *bool   `json:"noTableScan,omitempty"`
	OplogSizeMB                      *int64  `json:"oplogSizeMB,omitempty"`
	SampleSizeBIConnector            *int64  `json:"sampleSizeBIConnector,omitempty"`
	SampleRefreshIntervalBIConnector *int64  `json:"sampleRefreshIntervalBIConnector,omitempty"`
	OplogMinRetentionHours           *string `json:"oplogMinRetentionHours,omitempty"`
}

// ProcessArgsApplyConfiguration constructs a declarative configuration of the ProcessArgs type for use with
// apply.
func ProcessArgs() *ProcessArgsApplyConfiguration {
	return &ProcessArgsApplyConfiguration{}
}

// WithDefaultReadConcern sets the DefaultReadConcern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultReadConcern field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithDefaultReadConcern(value string) *ProcessArgsApplyConfiguration {
	b.DefaultReadConcern = &value
	return b
}

// WithDefaultWriteConcern sets the DefaultWriteConcern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultWriteConcern field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithDefaultWriteConcern(value string) *ProcessArgsApplyConfiguration {
	b.DefaultWriteConcern = &value
	return b
}

// WithMinimumEnabledTLSProtocol sets the MinimumEnabledTLSProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumEnabledTLSProtocol field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithMinimumEnabledTLSProtocol(value string) *ProcessArgsApplyConfiguration {
	b.MinimumEnabledTLSProtocol = &value
	return b
}

// WithFailIndexKeyTooLong sets the FailIndexKeyTooLong field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailIndexKeyTooLong field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithFailIndexKeyTooLong(value bool) *ProcessArgsApplyConfiguration {
	b.FailIndexKeyTooLong = &value
	return b
}

// WithJavascriptEnabled sets the JavascriptEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JavascriptEnabled field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithJavascriptEnabled(value bool) *ProcessArgsApplyConfiguration {
	b.JavascriptEnabled = &value
	return b
}

// WithNoTableScan sets the NoTableScan field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NoTableScan field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithNoTableScan(value bool) *ProcessArgsApplyConfiguration {
	b.NoTableScan = &value
	return b
}

// WithOplogSizeMB sets the OplogSizeMB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OplogSizeMB field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithOplogSizeMB(value int64) *ProcessArgsApplyConfiguration {
	b.OplogSizeMB = &value
	return b
}

// WithSampleSizeBIConnector sets the SampleSizeBIConnector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SampleSizeBIConnector field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithSampleSizeBIConnector(value int64) *ProcessArgsApplyConfiguration {
	b.SampleSizeBIConnector = &value
	return b
}

// WithSampleRefreshIntervalBIConnector sets the SampleRefreshIntervalBIConnector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SampleRefreshIntervalBIConnector field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithSampleRefreshIntervalBIConnector(value int64) *ProcessArgsApplyConfiguration {
	b.SampleRefreshIntervalBIConnector = &value
	return b
}

// WithOplogMinRetentionHours sets the OplogMinRetentionHours field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OplogMinRetentionHours field is set to the value of the last call.
func (b *ProcessArgsApplyConfiguration) WithOplogMinRetentionHours(value string) *ProcessArgsApplyConfiguration {
	b.OplogMinRetentionHours = &value
	return b
}
