//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// ProjectSettingsApplyConfiguration represents a declarative configuration of the ProjectSettings type for use
// with apply.
type ProjectSettingsApplyConfiguration struct {
	IsCollectDatabaseSpecificsStatisticsEnabled *bool `json:"isCollectDatabaseSpecificsStatisticsEnabled,omitempty"`
	IsDataExplorerEnabled                       *bool `json:"isDataExplorerEnabled,omitempty"`
	IsExtendedStorageSizesEnabled               *bool `json:"isExtendedStorageSizesEnabled,omitempty"`
	IsPerformanceAdvisorEnabled                 *bool `json:"isPerformanceAdvisorEnabled,omitempty"`
	IsRealtimePerformancePanelEnabled           *bool `json:"isRealtimePerformancePanelEnabled,omitempty"`
	IsSchemaAdvisorEnabled                      *bool `json:"isSchemaAdvisorEnabled,omitempty"`
}

// ProjectSettingsApplyConfiguration constructs a declarative configuration of the ProjectSettings type for use with
// apply.
func ProjectSettings() *ProjectSettingsApplyConfiguration {
	return &ProjectSettingsApplyConfiguration{}
}

// WithIsCollectDatabaseSpecificsStatisticsEnabled sets the IsCollectDatabaseSpecificsStatisticsEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsCollectDatabaseSpecificsStatisticsEnabled field is set to the value of the last call.
func (b *ProjectSettingsApplyConfiguration) WithIsCollectDatabaseSpecificsStatisticsEnabled(value bool) *ProjectSettingsApplyConfiguration {
	b.IsCollectDatabaseSpecificsStatisticsEnabled = &value
	return b
}

// WithIsDataExplorerEnabled sets the IsDataExplorerEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsDataExplorerEnabled field is set to the value of the last call.
func (b *ProjectSettingsApplyConfiguration) WithIsDataExplorerEnabled(value bool) *ProjectSettingsApplyConfiguration {
	b.IsDataExplorerEnabled = &value
	return b
}

// WithIsExtendedStorageSizesEnabled sets the IsExtendedStorageSizesEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsExtendedStorageSizesEnabled field is set to the value of the last call.
func (b *ProjectSettingsApplyConfiguration) WithIsExtendedStorageSizesEnabled(value bool) *ProjectSettingsApplyConfiguration {
	b.IsExtendedStorageSizesEnabled = &value
	return b
}

// WithIsPerformanceAdvisorEnabled sets the IsPerformanceAdvisorEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsPerformanceAdvisorEnabled field is set to the value of the last call.
func (b *ProjectSettingsApplyConfiguration) WithIsPerformanceAdvisorEnabled(value bool) *ProjectSettingsApplyConfiguration {
	b.IsPerformanceAdvisorEnabled = &value
	return b
}

// WithIsRealtimePerformancePanelEnabled sets the IsRealtimePerformancePanelEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsRealtimePerformancePanelEnabled field is set to the value of the last call.
func (b *ProjectSettingsApplyConfiguration) WithIsRealtimePerformancePanelEnabled(value bool) *ProjectSettingsApplyConfiguration {
	b.IsRealtimePerformancePanelEnabled = &value
	return b
}

// WithIsSchemaAdvisorEnabled sets the IsSchemaAdvisorEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsSchemaAdvisorEnabled field is set to the value of the last call.
func (b *ProjectSettingsApplyConfiguration) WithIsSchemaAdvisorEnabled(value bool) *ProjectSettingsApplyConfiguration {
	b.IsSchemaAdvisorEnabled = &value
	return b
}
