//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	api "github.com/mongodb/mongodb-atlas-kubernetes/v2/api"
	common "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/common"
)

// ProjectDualReferenceApplyConfiguration represents a declarative configuration of the ProjectDualReference type for use
// with apply.
type ProjectDualReferenceApplyConfiguration struct {
	ProjectRef         *common.ResourceRefNamespaced               `json:"projectRef,omitempty"`
	ExternalProjectRef *ExternalProjectReferenceApplyConfiguration `json:"externalProjectRef,omitempty"`
	ConnectionSecret   *api.LocalObjectReference                   `json:"connectionSecret,omitempty"`
}

// ProjectDualReferenceApplyConfiguration constructs a declarative configuration of the ProjectDualReference type for use with
// apply.
func ProjectDualReference() *ProjectDualReferenceApplyConfiguration {
	return &ProjectDualReferenceApplyConfiguration{}
}

// WithProjectRef sets the ProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectRef field is set to the value of the last call.
func (b *ProjectDualReferenceApplyConfiguration) WithProjectRef(value common.ResourceRefNamespaced) *ProjectDualReferenceApplyConfiguration {
	b.ProjectRef = &value
	return b
}

// WithExternalProjectRef sets the ExternalProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalProjectRef field is set to the value of the last call.
func (b *ProjectDualReferenceApplyConfiguration) WithExternalProjectRef(value *ExternalProjectReferenceApplyConfiguration) *ProjectDualReferenceApplyConfiguration {
	b.ExternalProjectRef = value
	return b
}

// WithConnectionSecret sets the ConnectionSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionSecret field is set to the value of the last call.
func (b *ProjectDualReferenceApplyConfiguration) WithConnectionSecret(value api.LocalObjectReference) *ProjectDualReferenceApplyConfiguration {
	b.ConnectionSecret = &value
	return b
}
