//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// SearchNodeApplyConfiguration represents a declarative configuration of the SearchNode type for use
// with apply.
type SearchNodeApplyConfiguration struct {
	InstanceSize *string `json:"instanceSize,omitempty"`
	NodeCount    *byte   `json:"nodeCount,omitempty"`
}

// SearchNodeApplyConfiguration constructs a declarative configuration of the SearchNode type for use with
// apply.
func SearchNode() *SearchNodeApplyConfiguration {
	return &SearchNodeApplyConfiguration{}
}

// WithInstanceSize sets the InstanceSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceSize field is set to the value of the last call.
func (b *SearchNodeApplyConfiguration) WithInstanceSize(value string) *SearchNodeApplyConfiguration {
	b.InstanceSize = &value
	return b
}

// WithNodeCount sets the NodeCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeCount field is set to the value of the last call.
func (b *SearchNodeApplyConfiguration) WithNodeCount(value byte) *SearchNodeApplyConfiguration {
	b.NodeCount = &value
	return b
}
