//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	provider "github.com/mongodb/mongodb-atlas-kubernetes/v2/api/v1/provider"
)

// ServerlessProviderSettingsSpecApplyConfiguration represents a declarative configuration of the ServerlessProviderSettingsSpec type for use
// with apply.
type ServerlessProviderSettingsSpecApplyConfiguration struct {
	BackingProviderName *string                            `json:"backingProviderName,omitempty"`
	DiskIOPS            *int64                             `json:"diskIOPS,omitempty"`
	DiskTypeName        *string                            `json:"diskTypeName,omitempty"`
	EncryptEBSVolume    *bool                              `json:"encryptEBSVolume,omitempty"`
	InstanceSizeName    *string                            `json:"instanceSizeName,omitempty"`
	ProviderName        *provider.ProviderName             `json:"providerName,omitempty"`
	RegionName          *string                            `json:"regionName,omitempty"`
	VolumeType          *string                            `json:"volumeType,omitempty"`
	AutoScaling         *AutoScalingSpecApplyConfiguration `json:"autoScaling,omitempty"`
}

// ServerlessProviderSettingsSpecApplyConfiguration constructs a declarative configuration of the ServerlessProviderSettingsSpec type for use with
// apply.
func ServerlessProviderSettingsSpec() *ServerlessProviderSettingsSpecApplyConfiguration {
	return &ServerlessProviderSettingsSpecApplyConfiguration{}
}

// WithBackingProviderName sets the BackingProviderName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackingProviderName field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithBackingProviderName(value string) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.BackingProviderName = &value
	return b
}

// WithDiskIOPS sets the DiskIOPS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskIOPS field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithDiskIOPS(value int64) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.DiskIOPS = &value
	return b
}

// WithDiskTypeName sets the DiskTypeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskTypeName field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithDiskTypeName(value string) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.DiskTypeName = &value
	return b
}

// WithEncryptEBSVolume sets the EncryptEBSVolume field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EncryptEBSVolume field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithEncryptEBSVolume(value bool) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.EncryptEBSVolume = &value
	return b
}

// WithInstanceSizeName sets the InstanceSizeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceSizeName field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithInstanceSizeName(value string) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.InstanceSizeName = &value
	return b
}

// WithProviderName sets the ProviderName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderName field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithProviderName(value provider.ProviderName) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.ProviderName = &value
	return b
}

// WithRegionName sets the RegionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RegionName field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithRegionName(value string) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.RegionName = &value
	return b
}

// WithVolumeType sets the VolumeType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeType field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithVolumeType(value string) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.VolumeType = &value
	return b
}

// WithAutoScaling sets the AutoScaling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoScaling field is set to the value of the last call.
func (b *ServerlessProviderSettingsSpecApplyConfiguration) WithAutoScaling(value *AutoScalingSpecApplyConfiguration) *ServerlessProviderSettingsSpecApplyConfiguration {
	b.AutoScaling = value
	return b
}
