//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// StoreApplyConfiguration represents a declarative configuration of the Store type for use
// with apply.
type StoreApplyConfiguration struct {
	Name                     *string  `json:"name,omitempty"`
	Provider                 *string  `json:"provider,omitempty"`
	AdditionalStorageClasses []string `json:"additionalStorageClasses,omitempty"`
	Bucket                   *string  `json:"bucket,omitempty"`
	Delimiter                *string  `json:"delimiter,omitempty"`
	IncludeTags              *bool    `json:"includeTags,omitempty"`
	Prefix                   *string  `json:"prefix,omitempty"`
	Public                   *bool    `json:"public,omitempty"`
	Region                   *string  `json:"region,omitempty"`
}

// StoreApplyConfiguration constructs a declarative configuration of the Store type for use with
// apply.
func Store() *StoreApplyConfiguration {
	return &StoreApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *StoreApplyConfiguration) WithName(value string) *StoreApplyConfiguration {
	b.Name = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *StoreApplyConfiguration) WithProvider(value string) *StoreApplyConfiguration {
	b.Provider = &value
	return b
}

// WithAdditionalStorageClasses adds the given value to the AdditionalStorageClasses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalStorageClasses field.
func (b *StoreApplyConfiguration) WithAdditionalStorageClasses(values ...string) *StoreApplyConfiguration {
	for i := range values {
		b.AdditionalStorageClasses = append(b.AdditionalStorageClasses, values[i])
	}
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *StoreApplyConfiguration) WithBucket(value string) *StoreApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithDelimiter sets the Delimiter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Delimiter field is set to the value of the last call.
func (b *StoreApplyConfiguration) WithDelimiter(value string) *StoreApplyConfiguration {
	b.Delimiter = &value
	return b
}

// WithIncludeTags sets the IncludeTags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncludeTags field is set to the value of the last call.
func (b *StoreApplyConfiguration) WithIncludeTags(value bool) *StoreApplyConfiguration {
	b.IncludeTags = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *StoreApplyConfiguration) WithPrefix(value string) *StoreApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithPublic sets the Public field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Public field is set to the value of the last call.
func (b *StoreApplyConfiguration) WithPublic(value bool) *StoreApplyConfiguration {
	b.Public = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *StoreApplyConfiguration) WithRegion(value string) *StoreApplyConfiguration {
	b.Region = &value
	return b
}
