//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// StorageApplyConfiguration represents a declarative configuration of the Storage type for use
// with apply.
type StorageApplyConfiguration struct {
	Databases []DatabaseApplyConfiguration `json:"databases,omitempty"`
	Stores    []StoreApplyConfiguration    `json:"stores,omitempty"`
}

// StorageApplyConfiguration constructs a declarative configuration of the Storage type for use with
// apply.
func Storage() *StorageApplyConfiguration {
	return &StorageApplyConfiguration{}
}

// WithDatabases adds the given value to the Databases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Databases field.
func (b *StorageApplyConfiguration) WithDatabases(values ...*DatabaseApplyConfiguration) *StorageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDatabases")
		}
		b.Databases = append(b.Databases, *values[i])
	}
	return b
}

// WithStores adds the given value to the Stores field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Stores field.
func (b *StorageApplyConfiguration) WithStores(values ...*StoreApplyConfiguration) *StorageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithStores")
		}
		b.Stores = append(b.Stores, *values[i])
	}
	return b
}
