//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package v1

// TokenizerApplyConfiguration represents a declarative configuration of the Tokenizer type for use
// with apply.
type TokenizerApplyConfiguration struct {
	Type           *string `json:"type,omitempty"`
	MaxGram        *int    `json:"maxGram,omitempty"`
	MinGram        *int    `json:"minGram,omitempty"`
	Group          *int    `json:"group,omitempty"`
	Pattern        *string `json:"pattern,omitempty"`
	MaxTokenLength *int    `json:"maxTokenLength,omitempty"`
}

// TokenizerApplyConfiguration constructs a declarative configuration of the Tokenizer type for use with
// apply.
func Tokenizer() *TokenizerApplyConfiguration {
	return &TokenizerApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *TokenizerApplyConfiguration) WithType(value string) *TokenizerApplyConfiguration {
	b.Type = &value
	return b
}

// WithMaxGram sets the MaxGram field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxGram field is set to the value of the last call.
func (b *TokenizerApplyConfiguration) WithMaxGram(value int) *TokenizerApplyConfiguration {
	b.MaxGram = &value
	return b
}

// WithMinGram sets the MinGram field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinGram field is set to the value of the last call.
func (b *TokenizerApplyConfiguration) WithMinGram(value int) *TokenizerApplyConfiguration {
	b.MinGram = &value
	return b
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *TokenizerApplyConfiguration) WithGroup(value int) *TokenizerApplyConfiguration {
	b.Group = &value
	return b
}

// WithPattern sets the Pattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pattern field is set to the value of the last call.
func (b *TokenizerApplyConfiguration) WithPattern(value string) *TokenizerApplyConfiguration {
	b.Pattern = &value
	return b
}

// WithMaxTokenLength sets the MaxTokenLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxTokenLength field is set to the value of the last call.
func (b *TokenizerApplyConfiguration) WithMaxTokenLength(value int) *TokenizerApplyConfiguration {
	b.MaxTokenLength = &value
	return b
}
