// Code generated by crd2go. DO NOT EDIT.

package v1

import (
	k8s "github.com/mongodb/mongodb-atlas-kubernetes/tools/crd2go/k8s"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func init() {
	SchemeBuilder.Register(&FlexCluster{})
	SchemeBuilder.Register(&FlexClusterList{})
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

type FlexCluster struct {
	metav1.TypeMeta `json:",inline"`

	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec FlexClusterSpec `json:"spec,omitempty"`

	Status FlexClusterStatus `json:"status,omitempty"`
}

type FlexClusterSpec struct {
	// V20250312 The spec of the flexcluster resource for version v20250312.
	V20250312 *FlexClusterSpecV20250312 `json:"v20250312,omitempty"`
}

type FlexClusterSpecV20250312 struct {
	// Entry The entry fields of the flexcluster resource spec. These fields can be set
	// for creating and updating flexclusters.
	Entry *FlexClusterSpecV20250312Entry `json:"entry,omitempty"`

	/*
	   GroupId Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

	   **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.
	*/
	GroupId *string `json:"groupId,omitempty"`

	/*
	   GroupRef A reference to a "Group" resource.
	   The value of "$.status.v20250312.id" will be used to set "groupId".
	   Mutually exclusive with the "groupId" property.
	*/
	GroupRef *k8s.LocalReference `json:"groupRef,omitempty"`
}

type FlexClusterSpecV20250312Entry struct {
	// Name Human-readable label that identifies the instance.
	Name string `json:"name"`

	// ProviderSettings Group of cloud provider settings that configure the provisioned
	// MongoDB flex cluster.
	ProviderSettings ProviderSettings `json:"providerSettings"`

	// Tags List that contains key-value pairs between 1 to 255 characters in length
	// for tagging and categorizing the instance.
	Tags *[]Tags `json:"tags,omitempty"`

	// TerminationProtectionEnabled Flag that indicates whether termination protection
	// is enabled on the cluster. If set to `true`, MongoDB Cloud won't delete the
	// cluster. If set to `false`, MongoDB Cloud will delete the cluster.
	TerminationProtectionEnabled *bool `json:"terminationProtectionEnabled,omitempty"`
}

type ProviderSettings struct {
	// BackingProviderName Cloud service provider on which MongoDB Cloud provisioned
	// the flex cluster.
	BackingProviderName string `json:"backingProviderName"`

	// RegionName Human-readable label that identifies the geographic location of your
	// MongoDB flex cluster. The region you choose can affect network latency for
	// clients accessing your databases. For a complete list of region names, see
	// [AWS](https://docs.atlas.mongodb.com/reference/amazon-aws/#std-label-amazon-aws),
	// [GCP](https://docs.atlas.mongodb.com/reference/google-gcp/), and
	// [Azure](https://docs.atlas.mongodb.com/reference/microsoft-azure/).
	RegionName string `json:"regionName"`
}

type FlexClusterStatus struct {
	// Conditions Represents the latest available observations of a resource's current
	// state.
	Conditions *[]metav1.Condition `json:"conditions,omitempty"`

	// V20250312 The last observed Atlas state of the flexcluster resource for version
	// v20250312.
	V20250312 *FlexClusterStatusV20250312 `json:"v20250312,omitempty"`
}

type FlexClusterStatusV20250312 struct {
	// BackupSettings Flex backup configuration.
	BackupSettings *DiskGB `json:"backupSettings,omitempty"`

	// ClusterType Flex cluster topology.
	ClusterType *string `json:"clusterType,omitempty"`

	// ConnectionStrings Collection of Uniform Resource Locators that point to the
	// MongoDB database.
	ConnectionStrings *V20250312ConnectionStrings `json:"connectionStrings,omitempty"`

	// CreateDate Date and time when MongoDB Cloud created this instance. This
	// parameter expresses its value in ISO 8601 format in UTC.
	CreateDate *string `json:"createDate,omitempty"`

	// GroupId Unique 24-hexadecimal character string that identifies the project.
	GroupId *string `json:"groupId,omitempty"`

	// Id Unique 24-hexadecimal digit string that identifies the instance.
	Id *string `json:"id,omitempty"`

	// MongoDBVersion Version of MongoDB that the instance runs.
	MongoDBVersion *string `json:"mongoDBVersion,omitempty"`

	// Name Human-readable label that identifies the instance.
	Name *string `json:"name,omitempty"`

	// ProviderSettings Group of cloud provider settings that configure the provisioned
	// MongoDB flex cluster.
	ProviderSettings V20250312ProviderSettings `json:"providerSettings"`

	// StateName Human-readable label that indicates the current operating condition of
	// this instance.
	StateName *string `json:"stateName,omitempty"`

	// VersionReleaseSystem Method by which the cluster maintains the MongoDB versions.
	VersionReleaseSystem *string `json:"versionReleaseSystem,omitempty"`
}

type V20250312ConnectionStrings struct {
	// Standard Public connection string that you can use to connect to this cluster.
	// This connection string uses the mongodb:// protocol.
	Standard *string `json:"standard,omitempty"`

	// StandardSrv Public connection string that you can use to connect to this flex
	// cluster. This connection string uses the `mongodb+srv://` protocol.
	StandardSrv *string `json:"standardSrv,omitempty"`
}

type V20250312ProviderSettings struct {
	// BackingProviderName Cloud service provider on which MongoDB Cloud provisioned
	// the flex cluster.
	BackingProviderName *string `json:"backingProviderName,omitempty"`

	// DiskSizeGB Storage capacity available to the flex cluster expressed in
	// gigabytes.
	DiskSizeGB *float64 `json:"diskSizeGB,omitempty"`

	// ProviderName Human-readable label that identifies the provider type.
	ProviderName *string `json:"providerName,omitempty"`

	// RegionName Human-readable label that identifies the geographic location of your
	// MongoDB flex cluster. The region you choose can affect network latency for
	// clients accessing your databases. For a complete list of region names, see
	// [AWS](https://docs.atlas.mongodb.com/reference/amazon-aws/#std-label-amazon-aws),
	// [GCP](https://docs.atlas.mongodb.com/reference/google-gcp/), and
	// [Azure](https://docs.atlas.mongodb.com/reference/microsoft-azure/).
	RegionName *string `json:"regionName,omitempty"`
}

// +kubebuilder:object:root=true
type FlexClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FlexCluster `json:"items"`
}
