// Code generated by mockery. DO NOT EDIT.

package translation

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	maintenancewindow "github.com/mongodb/mongodb-atlas-kubernetes/v2/internal/translation/maintenancewindow"
)

// MaintenanceWindowServiceMock is an autogenerated mock type for the MaintenanceWindowService type
type MaintenanceWindowServiceMock struct {
	mock.Mock
}

type MaintenanceWindowServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MaintenanceWindowServiceMock) EXPECT() *MaintenanceWindowServiceMock_Expecter {
	return &MaintenanceWindowServiceMock_Expecter{mock: &_m.Mock}
}

// Defer provides a mock function with given fields: _a0, _a1
func (_m *MaintenanceWindowServiceMock) Defer(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Defer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceWindowServiceMock_Defer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Defer'
type MaintenanceWindowServiceMock_Defer_Call struct {
	*mock.Call
}

// Defer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MaintenanceWindowServiceMock_Expecter) Defer(_a0 interface{}, _a1 interface{}) *MaintenanceWindowServiceMock_Defer_Call {
	return &MaintenanceWindowServiceMock_Defer_Call{Call: _e.mock.On("Defer", _a0, _a1)}
}

func (_c *MaintenanceWindowServiceMock_Defer_Call) Run(run func(_a0 context.Context, _a1 string)) *MaintenanceWindowServiceMock_Defer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MaintenanceWindowServiceMock_Defer_Call) Return(_a0 error) *MaintenanceWindowServiceMock_Defer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceWindowServiceMock_Defer_Call) RunAndReturn(run func(context.Context, string) error) *MaintenanceWindowServiceMock_Defer_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MaintenanceWindowServiceMock) Get(_a0 context.Context, _a1 string) (*maintenancewindow.MaintenanceWindow, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *maintenancewindow.MaintenanceWindow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*maintenancewindow.MaintenanceWindow, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *maintenancewindow.MaintenanceWindow); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*maintenancewindow.MaintenanceWindow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintenanceWindowServiceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MaintenanceWindowServiceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MaintenanceWindowServiceMock_Expecter) Get(_a0 interface{}, _a1 interface{}) *MaintenanceWindowServiceMock_Get_Call {
	return &MaintenanceWindowServiceMock_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *MaintenanceWindowServiceMock_Get_Call) Run(run func(_a0 context.Context, _a1 string)) *MaintenanceWindowServiceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MaintenanceWindowServiceMock_Get_Call) Return(_a0 *maintenancewindow.MaintenanceWindow, _a1 error) *MaintenanceWindowServiceMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MaintenanceWindowServiceMock_Get_Call) RunAndReturn(run func(context.Context, string) (*maintenancewindow.MaintenanceWindow, error)) *MaintenanceWindowServiceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields: _a0, _a1
func (_m *MaintenanceWindowServiceMock) Reset(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceWindowServiceMock_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MaintenanceWindowServiceMock_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MaintenanceWindowServiceMock_Expecter) Reset(_a0 interface{}, _a1 interface{}) *MaintenanceWindowServiceMock_Reset_Call {
	return &MaintenanceWindowServiceMock_Reset_Call{Call: _e.mock.On("Reset", _a0, _a1)}
}

func (_c *MaintenanceWindowServiceMock_Reset_Call) Run(run func(_a0 context.Context, _a1 string)) *MaintenanceWindowServiceMock_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MaintenanceWindowServiceMock_Reset_Call) Return(_a0 error) *MaintenanceWindowServiceMock_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceWindowServiceMock_Reset_Call) RunAndReturn(run func(context.Context, string) error) *MaintenanceWindowServiceMock_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleAutoDefer provides a mock function with given fields: _a0, _a1
func (_m *MaintenanceWindowServiceMock) ToggleAutoDefer(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ToggleAutoDefer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceWindowServiceMock_ToggleAutoDefer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleAutoDefer'
type MaintenanceWindowServiceMock_ToggleAutoDefer_Call struct {
	*mock.Call
}

// ToggleAutoDefer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MaintenanceWindowServiceMock_Expecter) ToggleAutoDefer(_a0 interface{}, _a1 interface{}) *MaintenanceWindowServiceMock_ToggleAutoDefer_Call {
	return &MaintenanceWindowServiceMock_ToggleAutoDefer_Call{Call: _e.mock.On("ToggleAutoDefer", _a0, _a1)}
}

func (_c *MaintenanceWindowServiceMock_ToggleAutoDefer_Call) Run(run func(_a0 context.Context, _a1 string)) *MaintenanceWindowServiceMock_ToggleAutoDefer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MaintenanceWindowServiceMock_ToggleAutoDefer_Call) Return(_a0 error) *MaintenanceWindowServiceMock_ToggleAutoDefer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceWindowServiceMock_ToggleAutoDefer_Call) RunAndReturn(run func(context.Context, string) error) *MaintenanceWindowServiceMock_ToggleAutoDefer_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *MaintenanceWindowServiceMock) Update(_a0 context.Context, _a1 string, _a2 *maintenancewindow.MaintenanceWindow) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *maintenancewindow.MaintenanceWindow) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaintenanceWindowServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MaintenanceWindowServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 *maintenancewindow.MaintenanceWindow
func (_e *MaintenanceWindowServiceMock_Expecter) Update(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MaintenanceWindowServiceMock_Update_Call {
	return &MaintenanceWindowServiceMock_Update_Call{Call: _e.mock.On("Update", _a0, _a1, _a2)}
}

func (_c *MaintenanceWindowServiceMock_Update_Call) Run(run func(_a0 context.Context, _a1 string, _a2 *maintenancewindow.MaintenanceWindow)) *MaintenanceWindowServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*maintenancewindow.MaintenanceWindow))
	})
	return _c
}

func (_c *MaintenanceWindowServiceMock_Update_Call) Return(_a0 error) *MaintenanceWindowServiceMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MaintenanceWindowServiceMock_Update_Call) RunAndReturn(run func(context.Context, string, *maintenancewindow.MaintenanceWindow) error) *MaintenanceWindowServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMaintenanceWindowServiceMock creates a new instance of MaintenanceWindowServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaintenanceWindowServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MaintenanceWindowServiceMock {
	mock := &MaintenanceWindowServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
