//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDConfig) DeepCopyInto(out *CRDConfig) {
	*out = *in
	out.GVK = in.GVK
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]CRDMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShortNames != nil {
		in, out := &in.ShortNames, &out.ShortNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDConfig.
func (in *CRDConfig) DeepCopy() *CRDConfig {
	if in == nil {
		return nil
	}
	out := new(CRDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDMapping) DeepCopyInto(out *CRDMapping) {
	*out = *in
	out.OpenAPIRef = in.OpenAPIRef
	out.ParametersMapping = in.ParametersMapping
	in.EntryMapping.DeepCopyInto(&out.EntryMapping)
	in.StatusMapping.DeepCopyInto(&out.StatusMapping)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDMapping.
func (in *CRDMapping) DeepCopy() *CRDMapping {
	if in == nil {
		return nil
	}
	out := new(CRDMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldMapping) DeepCopyInto(out *FieldMapping) {
	*out = *in
	out.Path = in.Path
	in.Filters.DeepCopyInto(&out.Filters)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldMapping.
func (in *FieldMapping) DeepCopy() *FieldMapping {
	if in == nil {
		return nil
	}
	out := new(FieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldPath) DeepCopyInto(out *FieldPath) {
	*out = *in
	out.RequestBody = in.RequestBody
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldPath.
func (in *FieldPath) DeepCopy() *FieldPath {
	if in == nil {
		return nil
	}
	out := new(FieldPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filters) DeepCopyInto(out *Filters) {
	*out = *in
	if in.SkipProperties != nil {
		in, out := &in.SkipProperties, &out.SkipProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SensitiveProperties != nil {
		in, out := &in.SensitiveProperties, &out.SensitiveProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filters.
func (in *Filters) DeepCopy() *Filters {
	if in == nil {
		return nil
	}
	out := new(Filters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAPIDefinition) DeepCopyInto(out *OpenAPIDefinition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAPIDefinition.
func (in *OpenAPIDefinition) DeepCopy() *OpenAPIDefinition {
	if in == nil {
		return nil
	}
	out := new(OpenAPIDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersMapping) DeepCopyInto(out *ParametersMapping) {
	*out = *in
	out.FieldPath = in.FieldPath
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersMapping.
func (in *ParametersMapping) DeepCopy() *ParametersMapping {
	if in == nil {
		return nil
	}
	out := new(ParametersMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestBody) DeepCopyInto(out *RequestBody) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestBody.
func (in *RequestBody) DeepCopy() *RequestBody {
	if in == nil {
		return nil
	}
	out := new(RequestBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spec) DeepCopyInto(out *Spec) {
	*out = *in
	if in.CRDConfig != nil {
		in, out := &in.CRDConfig, &out.CRDConfig
		*out = make([]CRDConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OpenAPIDefinitions != nil {
		in, out := &in.OpenAPIDefinitions, &out.OpenAPIDefinitions
		*out = make([]OpenAPIDefinition, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spec.
func (in *Spec) DeepCopy() *Spec {
	if in == nil {
		return nil
	}
	out := new(Spec)
	in.DeepCopyInto(out)
	return out
}
