{{- if and (not .Values.atlas.secret.global) (not .Values.atlas.secret.existing) }}
{{- if and .Values.atlas.secret.publicApiKey .Values.atlas.secret.clientSecret }}
{{- fail "atlas.secret: set either (publicApiKey,privateApiKey) or (clientId,clientSecret), not both" }}
{{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
{{- if .Values.atlas.secret.setCustomName }}
  name: {{ .Values.atlas.secret.setCustomName}}
{{- else }}
  name: {{ include "atlas-deployment.fullname" . }}-secret
{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    atlas.mongodb.com/type: "credentials"
    {{- include "atlas-deployment.labels" . | nindent 4 }}
  annotations:
    'helm.sh/hook': post-delete,pre-install,pre-upgrade
data:
    orgId: {{ .Values.atlas.secret.orgId | b64enc }}
    {{- if .Values.atlas.secret.clientSecret }}
    clientId: {{ .Values.atlas.secret.clientId | b64enc }}
    clientSecret: {{ .Values.atlas.secret.clientSecret | b64enc }}
    {{- else }}
    publicApiKey: {{ .Values.atlas.secret.publicApiKey | b64enc }}
    privateApiKey: {{ .Values.atlas.secret.privateApiKey | b64enc }}
    {{- end }}
{{- end }}
