// Copyright 2025 MongoDB Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package status

import (
	"github.com/mongodb/mongodb-atlas-kubernetes/v2/api"
)

// DataFederationStatus defines the observed state of AtlasDataFederation.
type DataFederationStatus struct {
	api.Common `json:",inline"`

	// MongoDBVersion is the version of MongoDB the cluster runs, in <major version>.<minor version> format.
	MongoDBVersion string `json:"mongoDBVersion,omitempty"`
	// CloudProviderConfig holds Atlas-assigned read-only fields for the cloud provider configuration.
	// +optional
	CloudProviderConfig *DataFederationCloudProviderConfigStatus `json:"cloudProviderConfig,omitempty"`
}

// DataFederationCloudProviderConfigStatus holds Atlas-assigned read-only fields per cloud provider.
type DataFederationCloudProviderConfigStatus struct {
	// AWS holds Atlas-assigned read-only fields for the AWS cloud provider config.
	// +optional
	AWS *AWSProviderConfigStatus `json:"aws,omitempty"`
	// Azure holds Atlas-assigned read-only fields for the Azure cloud provider config.
	// +optional
	Azure *AzureProviderConfigStatus `json:"azure,omitempty"`
	// GCP holds Atlas-assigned read-only fields for the GCP cloud provider config.
	// +optional
	GCP *GCPProviderConfigStatus `json:"gcp,omitempty"`
}

// AWSProviderConfigStatus holds Atlas-assigned read-only IAM fields for AWS.
type AWSProviderConfigStatus struct {
	// ExternalID is the IAM role external ID assigned by Atlas.
	ExternalID string `json:"externalId,omitempty"`
	// IAMAssumedRoleARN is the ARN of the IAM role Atlas assumes when accessing data stores.
	IAMAssumedRoleARN string `json:"iamAssumedRoleARN,omitempty"`
	// IAMUserARN is the ARN of the IAM user Atlas assumes when accessing data stores.
	IAMUserARN string `json:"iamUserARN,omitempty"`
}

// AzureProviderConfigStatus holds Atlas-assigned read-only fields for Azure.
type AzureProviderConfigStatus struct {
	// AtlasAppID is the App ID generated by Atlas for the Service Principal's access policy.
	AtlasAppID string `json:"atlasAppId,omitempty"`
	// ServicePrincipalID is the ID of the Service Principal Atlas uses to access Azure resources.
	ServicePrincipalID string `json:"servicePrincipalId,omitempty"`
	// TenantID is the Azure Active Directory tenant ID of the Service Principal.
	TenantID string `json:"tenantId,omitempty"`
}

// GCPProviderConfigStatus holds Atlas-assigned read-only fields for GCP.
type GCPProviderConfigStatus struct {
	// GCPServiceAccount is the email of the GCP service account created by Atlas.
	GCPServiceAccount string `json:"gcpServiceAccount,omitempty"`
}

// +k8s:deepcopy-gen=false

type DataFederationStatusOption func(s *DataFederationStatus)
