//go:build !ignore_autogenerated

/*
Copyright (C) MongoDB, Inc. 2020-present.

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package status

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasAuditingStatus) DeepCopyInto(out *AtlasAuditingStatus) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]ProjectAuditingStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasAuditingStatus.
func (in *AtlasAuditingStatus) DeepCopy() *AtlasAuditingStatus {
	if in == nil {
		return nil
	}
	out := new(AtlasAuditingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectAuditingStatus) DeepCopyInto(out *ProjectAuditingStatus) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectAuditingStatus.
func (in *ProjectAuditingStatus) DeepCopy() *ProjectAuditingStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectAuditingStatus)
	in.DeepCopyInto(out)
	return out
}
