//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"

	generatedv1 "github.com/mongodb/mongodb-atlas-kubernetes/v2/internal/nextapi/applyconfiguration/generated/v1"
	internal "github.com/mongodb/mongodb-atlas-kubernetes/v2/internal/nextapi/applyconfiguration/internal"
	v1 "github.com/mongodb/mongodb-atlas-kubernetes/v2/internal/nextapi/generated/v1"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=atlas.generated.mongodb.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("AdvancedConfiguration"):
		return &generatedv1.AdvancedConfigurationApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("AnalyticsAutoScaling"):
		return &generatedv1.AnalyticsAutoScalingApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("AnalyticsSpecs"):
		return &generatedv1.AnalyticsSpecsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("BiConnector"):
		return &generatedv1.BiConnectorApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Cluster"):
		return &generatedv1.ClusterApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ClusterSpec"):
		return &generatedv1.ClusterSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ClusterSpecV20250312"):
		return &generatedv1.ClusterSpecV20250312ApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ClusterStatus"):
		return &generatedv1.ClusterStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ClusterStatusV20250312"):
		return &generatedv1.ClusterStatusV20250312ApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Compute"):
		return &generatedv1.ComputeApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ConnectionStrings"):
		return &generatedv1.ConnectionStringsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DatabaseUser"):
		return &generatedv1.DatabaseUserApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DatabaseUserSpec"):
		return &generatedv1.DatabaseUserSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DatabaseUserSpecV20250312"):
		return &generatedv1.DatabaseUserSpecV20250312ApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DatabaseUserSpecV20250312Entry"):
		return &generatedv1.DatabaseUserSpecV20250312EntryApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DatabaseUserStatus"):
		return &generatedv1.DatabaseUserStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DiskGB"):
		return &generatedv1.DiskGBApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ElectableSpecs"):
		return &generatedv1.ElectableSpecsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Endpoints"):
		return &generatedv1.EndpointsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Entry"):
		return &generatedv1.EntryApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FlexCluster"):
		return &generatedv1.FlexClusterApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FlexClusterSpec"):
		return &generatedv1.FlexClusterSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FlexClusterSpecV20250312"):
		return &generatedv1.FlexClusterSpecV20250312ApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FlexClusterSpecV20250312Entry"):
		return &generatedv1.FlexClusterSpecV20250312EntryApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FlexClusterStatus"):
		return &generatedv1.FlexClusterStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FlexClusterStatusV20250312"):
		return &generatedv1.FlexClusterStatusV20250312ApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Group"):
		return &generatedv1.GroupApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("GroupSpec"):
		return &generatedv1.GroupSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("GroupStatus"):
		return &generatedv1.GroupStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("GroupStatusV20250312"):
		return &generatedv1.GroupStatusV20250312ApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Links"):
		return &generatedv1.LinksApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MongoDBEmployeeAccessGrant"):
		return &generatedv1.MongoDBEmployeeAccessGrantApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("PasswordSecretRef"):
		return &generatedv1.PasswordSecretRefApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("PrivateEndpoint"):
		return &generatedv1.PrivateEndpointApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ProviderSettings"):
		return &generatedv1.ProviderSettingsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("RegionConfigs"):
		return &generatedv1.RegionConfigsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ReplicationSpecs"):
		return &generatedv1.ReplicationSpecsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ReplicationSpecsRegionConfigs"):
		return &generatedv1.ReplicationSpecsRegionConfigsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Roles"):
		return &generatedv1.RolesApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Scopes"):
		return &generatedv1.ScopesApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Tags"):
		return &generatedv1.TagsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("V20250312"):
		return &generatedv1.V20250312ApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("V20250312ConnectionStrings"):
		return &generatedv1.V20250312ConnectionStringsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("V20250312Entry"):
		return &generatedv1.V20250312EntryApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("V20250312ProviderSettings"):
		return &generatedv1.V20250312ProviderSettingsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("V20250312ReplicationSpecs"):
		return &generatedv1.V20250312ReplicationSpecsApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
