// Code generated by crd2go. DO NOT EDIT.

package v1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

func init() {
	SchemeBuilder.Register(&Group{})
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ThirdPartyIntegration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ThirdPartyIntegrationSpec   `json:"spec,omitempty"`
	Status ThirdPartyIntegrationStatus `json:"status,omitempty"`
}

type ThirdPartyIntegrationSpec struct {
	// V20241113 The spec of the thirdpartyintegration resource for version v20241113.
	V20241113 *ThirdPartyIntegrationSpecV20241113 `json:"v20241113,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113 struct {
	// Entry The entry fields of the thirdpartyintegration resource spec. These fields
	// can be set for creating and updating thirdpartyintegrations.
	Entry *ThirdPartyIntegrationSpecV20241113Entry `json:"entry,omitempty"`

	// Parameters The parameter fields of the thirdpartyintegration resource spec.
	// These fields are used when creating thirdpartyintegrations only.
	Parameters *ThirdPartyIntegrationSpecV20241113Parameters `json:"parameters,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113Entry struct {
	// AccountId Unique 40-hexadecimal digit string that identifies your New Relic
	// account.
	AccountId *string `json:"accountId,omitempty"`

	/*
	   ApiKeyRef SENSITIVE FIELD

	   Reference to a secret containing data for the "apiKey" field:

	   Key that allows MongoDB Cloud to access your VictorOps account.

	   **NOTE**: After you create a notification which requires an API or integration key, the key appears partially redacted when you:

	   * View or edit the alert through the Atlas UI.

	   * Query the alert for the notification through the Atlas Administration API.
	*/
	ApiKeyRef *ThirdPartyIntegrationSpecV20241113EntryApiKeyRef `json:"apiKeyRef,omitempty"`

	/*
	   ApiTokenRef SENSITIVE FIELD

	   Reference to a secret containing data for the "apiToken" field:

	   Key that allows MongoDB Cloud to access your Slack account.

	   **NOTE**: After you create a notification which requires an API or integration key, the key appears partially redacted when you:

	   * View or edit the alert through the Atlas UI.

	   * Query the alert for the notification through the Atlas Administration API.

	   **IMPORTANT**: Slack integrations now use the OAuth2 verification method and must  be initially configured, or updated from a legacy integration, through the Atlas  third-party service integrations page. Legacy tokens will soon no longer be  supported.
	*/
	ApiTokenRef *ThirdPartyIntegrationSpecV20241113EntryApiTokenRef `json:"apiTokenRef,omitempty"`

	// ChannelName Name of the Slack channel to which MongoDB Cloud sends alert
	// notifications.
	ChannelName *string `json:"channelName,omitempty"`

	// Enabled Flag that indicates whether someone has activated the Prometheus
	// integration.
	Enabled *bool `json:"enabled,omitempty"`

	/*
	   LicenseKeyRef SENSITIVE FIELD

	   Reference to a secret containing data for the "licenseKey" field:

	   Unique 40-hexadecimal digit string that identifies your New Relic license.

	   **IMPORTANT**: Effective Wednesday, June 16th, 2021, New Relic no longer supports the plugin-based integration with MongoDB. We do not recommend that you sign up for the plugin-based integration.
	   To learn more, see the <a href="https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267" target="_blank">New Relic Plugin EOL Statement</a> Consider configuring an alternative monitoring integration before June 16th to maintain visibility into your MongoDB deployments.
	*/
	LicenseKeyRef *ThirdPartyIntegrationSpecV20241113EntryLicenseKeyRef `json:"licenseKeyRef,omitempty"`

	/*
	   MicrosoftTeamsWebhookUrlRef SENSITIVE FIELD

	   Reference to a secret containing data for the "microsoftTeamsWebhookUrl" field:

	   Endpoint web address of the Microsoft Teams webhook to which MongoDB Cloud sends notifications.

	   **NOTE**: When you view or edit the alert for a Microsoft Teams notification, the URL appears partially redacted.
	*/
	MicrosoftTeamsWebhookUrlRef *ThirdPartyIntegrationSpecV20241113EntryMicrosoftTeamsWebhookUrlRef `json:"microsoftTeamsWebhookUrlRef,omitempty"`

	/*
	   PasswordRef SENSITIVE FIELD

	   Reference to a secret containing data for the "password" field:

	   Password needed to allow MongoDB Cloud to access your Prometheus account.
	*/
	PasswordRef *ThirdPartyIntegrationSpecV20241113EntryPasswordRef `json:"passwordRef,omitempty"`

	/*
	   ReadTokenRef SENSITIVE FIELD

	   Reference to a secret containing data for the "readToken" field:

	   Query key used to access your New Relic account.
	*/
	ReadTokenRef *ThirdPartyIntegrationSpecV20241113EntryReadTokenRef `json:"readTokenRef,omitempty"`

	// Region PagerDuty region that indicates the API Uniform Resource Locator (URL) to
	// use.
	Region *string `json:"region,omitempty"`

	/*
	   RoutingKeyRef SENSITIVE FIELD

	   Reference to a secret containing data for the "routingKey" field:

	   Routing key associated with your Splunk On-Call account.
	*/
	RoutingKeyRef *ThirdPartyIntegrationSpecV20241113EntryRoutingKeyRef `json:"routingKeyRef,omitempty"`

	/*
	   SecretRef SENSITIVE FIELD

	   Reference to a secret containing data for the "secret" field:

	   An optional field returned if your webhook is configured with a secret.

	   **NOTE**: When you view or edit the alert for a webhook notification, the secret appears completely redacted.
	*/
	SecretRef *ThirdPartyIntegrationSpecV20241113EntrySecretRef `json:"secretRef,omitempty"`

	// ServiceDiscovery Desired method to discover the Prometheus service.
	ServiceDiscovery *string `json:"serviceDiscovery,omitempty"`

	/*
	   ServiceKeyRef SENSITIVE FIELD

	   Reference to a secret containing data for the "serviceKey" field:

	   Service key associated with your PagerDuty account.

	   **NOTE**: After you create a notification which requires an API or integration key, the key appears partially redacted when you:

	   * View or edit the alert through the Atlas UI.

	   * Query the alert for the notification through the Atlas Administration API.
	*/
	ServiceKeyRef *ThirdPartyIntegrationSpecV20241113EntryServiceKeyRef `json:"serviceKeyRef,omitempty"`

	// TeamName Human-readable label that identifies your Slack team. Set this
	// parameter when you configure a legacy Slack integration.
	TeamName *string `json:"teamName,omitempty"`

	// Type Human-readable label that identifies the service to which you want to
	// integrate with MongoDB Cloud. The value must match the third-party service
	// integration type.
	Type *string `json:"type,omitempty"`

	/*
	   UrlRef SENSITIVE FIELD

	   Reference to a secret containing data for the "url" field:

	   Endpoint web address to which MongoDB Cloud sends notifications.

	   **NOTE**: When you view or edit the alert for a webhook notification, the URL appears partially redacted.
	*/
	UrlRef *ThirdPartyIntegrationSpecV20241113EntryUrlRef `json:"urlRef,omitempty"`

	// Username Human-readable label that identifies your Prometheus incoming webhook.
	Username *string `json:"username,omitempty"`

	/*
	   WriteTokenRef SENSITIVE FIELD

	   Reference to a secret containing data for the "writeToken" field:

	   Insert key associated with your New Relic account.
	*/
	WriteTokenRef *ThirdPartyIntegrationSpecV20241113EntryWriteTokenRef `json:"writeTokenRef,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryApiKeyRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "apiKey".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryApiTokenRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "apiToken".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryLicenseKeyRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "licenseKey".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryMicrosoftTeamsWebhookUrlRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "microsoftTeamsWebhookUrl".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryPasswordRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "password".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryReadTokenRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "readToken".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryRoutingKeyRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "routingKey".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntrySecretRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "secret".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryServiceKeyRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "serviceKey".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryUrlRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "url".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113EntryWriteTokenRef struct {
	// Key Key of the secret data containing the sensitive field value, defaults to
	// "writeToken".
	Key *string `json:"key,omitempty"`

	// Name Name of the secret containing the sensitive field value.
	Name *string `json:"name,omitempty"`
}

type ThirdPartyIntegrationSpecV20241113Parameters struct {
	/*
	   GroupId Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

	   **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.
	*/
	GroupId *string `json:"groupId,omitempty"`

	// IntegrationType Human-readable label that identifies the service which you want
	// to integrate with MongoDB Cloud.
	IntegrationType *string `json:"integrationType,omitempty"`
}

type ThirdPartyIntegrationStatus struct {
	// Conditions Represents the latest available observations of a resource's current
	// state.
	Conditions *[]ThirdPartyIntegrationStatusConditions `json:"conditions,omitempty"`

	// V20241113 The last observed Atlas state of the thirdpartyintegration resource
	// for version v20241113.
	V20241113 *ThirdPartyIntegrationStatusV20241113 `json:"v20241113,omitempty"`
}

type ThirdPartyIntegrationStatusConditions struct {
	// LastTransitionTime Last time the condition transitioned from one status to
	// another.
	LastTransitionTime *string `json:"lastTransitionTime,omitempty"`

	// Message A human readable message indicating details about the transition.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration observedGeneration represents the .metadata.generation that
	// the condition was set based upon.
	ObservedGeneration *int `json:"observedGeneration,omitempty"`

	// Reason The reason for the condition's last transition.
	Reason *string `json:"reason,omitempty"`

	// Status Status of the condition, one of True, False, Unknown.
	Status string `json:"status"`

	// Type Type of condition.
	Type string `json:"type"`
}

type ThirdPartyIntegrationStatusV20241113 struct {
	// Id Integration id.
	Id *string `json:"id,omitempty"`

	// Type Human-readable label that identifies the service to which you want to
	// integrate with MongoDB Cloud. The value must match the third-party service
	// integration type.
	Type *string `json:"type,omitempty"`
}
