//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Group) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpec) DeepCopyInto(out *GroupSpec) {
	*out = *in
	if in.V20231115 != nil {
		in, out := &in.V20231115, &out.V20231115
		*out = new(GroupSpecV20231115)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpec.
func (in *GroupSpec) DeepCopy() *GroupSpec {
	if in == nil {
		return nil
	}
	out := new(GroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpecV20231115) DeepCopyInto(out *GroupSpecV20231115) {
	*out = *in
	if in.Entry != nil {
		in, out := &in.Entry, &out.Entry
		*out = new(GroupSpecV20231115Entry)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(GroupSpecV20231115Parameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpecV20231115.
func (in *GroupSpecV20231115) DeepCopy() *GroupSpecV20231115 {
	if in == nil {
		return nil
	}
	out := new(GroupSpecV20231115)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpecV20231115Entry) DeepCopyInto(out *GroupSpecV20231115Entry) {
	*out = *in
	if in.RegionUsageRestrictions != nil {
		in, out := &in.RegionUsageRestrictions, &out.RegionUsageRestrictions
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new([]GroupSpecV20231115EntryTags)
		if **in != nil {
			in, out := *in, *out
			*out = make([]GroupSpecV20231115EntryTags, len(*in))
			copy(*out, *in)
		}
	}
	if in.WithDefaultAlertsSettings != nil {
		in, out := &in.WithDefaultAlertsSettings, &out.WithDefaultAlertsSettings
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpecV20231115Entry.
func (in *GroupSpecV20231115Entry) DeepCopy() *GroupSpecV20231115Entry {
	if in == nil {
		return nil
	}
	out := new(GroupSpecV20231115Entry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpecV20231115EntryTags) DeepCopyInto(out *GroupSpecV20231115EntryTags) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpecV20231115EntryTags.
func (in *GroupSpecV20231115EntryTags) DeepCopy() *GroupSpecV20231115EntryTags {
	if in == nil {
		return nil
	}
	out := new(GroupSpecV20231115EntryTags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpecV20231115Parameters) DeepCopyInto(out *GroupSpecV20231115Parameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpecV20231115Parameters.
func (in *GroupSpecV20231115Parameters) DeepCopy() *GroupSpecV20231115Parameters {
	if in == nil {
		return nil
	}
	out := new(GroupSpecV20231115Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new([]GroupStatusConditions)
		if **in != nil {
			in, out := *in, *out
			*out = make([]GroupStatusConditions, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.V20231115 != nil {
		in, out := &in.V20231115, &out.V20231115
		*out = new(GroupStatusV20231115)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus.
func (in *GroupStatus) DeepCopy() *GroupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatusConditions) DeepCopyInto(out *GroupStatusConditions) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatusConditions.
func (in *GroupStatusConditions) DeepCopy() *GroupStatusConditions {
	if in == nil {
		return nil
	}
	out := new(GroupStatusConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatusV20231115) DeepCopyInto(out *GroupStatusV20231115) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatusV20231115.
func (in *GroupStatusV20231115) DeepCopy() *GroupStatusV20231115 {
	if in == nil {
		return nil
	}
	out := new(GroupStatusV20231115)
	in.DeepCopyInto(out)
	return out
}
