package crd2go

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	apiextensions "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

const (
	FirstVersion = ""

	CommentMaxWidth = 80
)

const (
	metav1Package = "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CodeWriterFunc is a function type that takes a CRD and returns a writer for the generated code
type CodeWriterFunc func(*apiextensions.CustomResourceDefinition) (io.WriteCloser, error)

// CodeFileForCRDAtPath creates a file writer for the given CRD at the specified directory
func CodeFileForCRDAtPath(dir string) CodeWriterFunc {
	return func(crd *apiextensions.CustomResourceDefinition) (io.WriteCloser, error) {
		crdName := strings.ToLower(crd.Spec.Names.Kind)
		srcFile := filepath.Join(dir, fmt.Sprintf("%s.go", crdName))
		w, err := os.Create(srcFile)
		if err != nil {
			return nil, fmt.Errorf("failed to create file %s: %w", srcFile, err)
		}
		return w, nil
	}
}

// GenerateStream generates Go code from a stream of CRDs within a YAML reader.
// It uses the provided CodeWriterFunc to write the generated code to the specified output.
// The version parameter specifies the version of the CRD to generate code for.
// The preloadedTypes parameter allows for preloading specific types to avoid name collisions.
func GenerateStream(cwFn CodeWriterFunc, r io.Reader, version string, preloadedTypes ...*GoType) error {
	generated := false
	scanner := bufio.NewScanner(r)
	td := NewTypeDict(preloadedTypes...)
	for {
		crd, err := ParseCRD(scanner)
		if errors.Is(err, io.EOF) {
			if generated {
				return nil
			}
			return err
		}
		if err != nil {
			return fmt.Errorf("failed to read input: %w", err)
		}
		w, err := cwFn(crd)
		if err != nil {
			return fmt.Errorf("failed to get writer for CRD %s: %w", crd.Name, err)
		}
		defer w.Close()
		stmt, err := generateCRD(td, crd, version)
		if err != nil {
			return fmt.Errorf("failed to generate CRD code: %w", err)
		}
		if _, err := w.Write(([]byte)(stmt.GoString())); err != nil {
			return fmt.Errorf("failed to write Go code: %w", err)
		}
		generated = true
	}
}

// generateCRD generates Go code for a CustomResourceDefinition (CRD) using the provided TypeDict and version
func generateCRD(td TypeDict, crd *apiextensions.CustomResourceDefinition, version string) (*jen.File, error) {
	v := selectVersion(&crd.Spec, version)
	if v == nil {
		if version == "" {
			return nil, fmt.Errorf("no versions to generate code from")
		}
		return nil, fmt.Errorf("no version %q to generate code from", version)
	}
	f := jen.NewFile(v.Name)
	f.HeaderComment("Code generated by crd2go. DO NOT EDIT.")
	f.ImportAlias(metav1Package, "metav1")
	f.Func().Id("init").Params().Block(
		jen.Id("SchemeBuilder").Dot("Register").Params(
			jen.Op("&").Id(crd.Spec.Names.Kind).Values(),
		),
	)

	if err := generateCRDRootObject(f, td, crd, v); err != nil {
		return nil, fmt.Errorf("failed to generate root object: %w", err)
	}
	return f, nil
}

// generateCRDRootObject generates the root object for the CRD
func generateCRDRootObject(f *jen.File, td TypeDict, crd *apiextensions.CustomResourceDefinition, v *apiextensions.CustomResourceDefinitionVersion) error {
	f.Comment("+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object")
	f.Comment("+kubebuilder:object:root=true").Line()

	specType := fmt.Sprintf("%sSpec", crd.Spec.Names.Kind)
	statusType := fmt.Sprintf("%sStatus", crd.Spec.Names.Kind)

	code := f.Type().Id(crd.Spec.Names.Kind).Struct(
		jen.Qual(metav1Package, "TypeMeta").Tag(map[string]string{"json": ",inline"}),
		jen.Qual(metav1Package, "ObjectMeta").Tag(map[string]string{"json": "metadata,omitempty"}),
		jen.Line(),
		jen.Id("Spec").Id(specType).Tag(map[string]string{"json": "spec,omitempty"}),
		jen.Id("Status").Id(statusType).Tag(map[string]string{"json": "status,omitempty"}),
	)

	specSchema := v.Schema.OpenAPIV3Schema.Properties["spec"]
	spec, err := FromOpenAPIType(td, specType, []string{crd.Spec.Names.Kind}, &specSchema)
	if err != nil {
		return fmt.Errorf("failed to generate spec type: %w", err)
	}
	specCode, err := generateType(td, spec)
	if err != nil {
		return fmt.Errorf("failed to generate spec code: %w", err)
	}
	code.Add(specCode)

	statusSchema := v.Schema.OpenAPIV3Schema.Properties["status"]
	status, err := FromOpenAPIType(td, statusType, []string{crd.Spec.Names.Kind}, &statusSchema)
	if err != nil {
		return fmt.Errorf("failed to generate status code: %w", err)
	}
	statusCode, err := generateType(td, status)
	if err != nil {
		return fmt.Errorf("failed to generate status code: %w", err)
	}
	code.Add(statusCode)
	return nil
}

// generateType generates Go code for a given type using the provided TypeDict
func generateType(td TypeDict, t *GoType) (*jen.Statement, error) {
	if t.Import != nil { // do not generate code for known imported types
		return jen.Null(), nil
	}
	if t.Kind == StructKind {
		return generateStructType(td, t)
	}
	if t.Kind == ArrayKind {
		return generateArrayType(td, t)
	}
	return nil, fmt.Errorf("unsupported type %q", t.Kind)
}

// generateStructType generates Go code for a struct type
func generateStructType(td TypeDict, t *GoType) (*jen.Statement, error) {
	fields := make([]jen.Code, 0, len(t.Fields))
	subtypes := make([]jen.Code, 0, len(t.Fields))
	for _, field := range t.Fields {
		fieldCode, err := generateField(field)
		if err != nil {
			return nil, fmt.Errorf("failed to generate field %s: %w", field.Name, err)
		}
		fields = append(fields, fieldCode)
		subtype, err := generateSubtype(td, field.GoType)
		if err != nil {
			return nil, fmt.Errorf("failed to generate field %s subtype: %w", field.Name, err)
		}
		subtypes = append(subtypes, subtype)
	}
	return jen.Line().Line().Type().Id(t.Name).Struct(fields...).Add(subtypes...), nil
}

// generateArrayType generates Go code for an array type
func generateArrayType(td TypeDict, t *GoType) (*jen.Statement, error) {
	elementType, err := generateSubtype(td, t.Element)
	if err != nil {
		return nil, fmt.Errorf("failed to generate array subtype: %w", err)
	}
	return elementType, nil
}

// generateSubtype generates Go code for a subtype of a given type
func generateSubtype(td TypeDict, t *GoType) (*jen.Statement, error) {
	if !t.isPrimitive() && !td.WasGenerated(t) {
		subtypeCode, err := generateType(td, t)
		if err != nil {
			return nil, fmt.Errorf("failed to generate subtype %s: %w", t.Name, err)
		}
		td.MarkGenerated(t)
		return subtypeCode, nil
	}
	return jen.Null(), nil
}

// generateField generates Go code for a field in a struct
func generateField(f *GoField) (jen.Code, error) {
	if f.GoType == nil {
		return nil, fmt.Errorf("field %q has no Go type", f.Name)
	}
	typeRefCode, err := qualifyRequired(generateTypeRef(f.GoType), f.Required)
	if err != nil {
		return nil, fmt.Errorf("failed to generate field type: %w", err)
	}
	fieldCode := jen.Null()
	if f.Comment != "" {
		fieldCode = generateFieldComment(fieldCode, f.Name, f.Comment)
	}
	return fieldCode.Id(f.Name).Add(typeRefCode).Add(generateJSONTag(f)).Line(), nil
}

// generateFieldComment generates a comment for a field in a struct
func generateFieldComment(code *jen.Statement, name, comment string) *jen.Statement {
	goComment := fmt.Sprintf("%s %s", name, comment)
	lines := formatComment(goComment, CommentMaxWidth)
	for _, line := range lines {
		code.Add(jen.Comment(line).Line())
	}
	return code
}

// qualifyRequired qualifies the type reference based on whether the field is required
func qualifyRequired(typeRef *jen.Statement, required bool) (*jen.Statement, error) {
	if required {
		return typeRef, nil
	}
	return jen.Op("*").Add(typeRef), nil
}

// generateTypeRef generates a type reference for a given GoType
func generateTypeRef(t *GoType) *jen.Statement {
	switch t.Kind {
	case StringKind:
		return jen.String()
	case IntKind:
		return jen.Int()
	case FloatKind:
		return jen.Float64()
	case BoolKind:
		return jen.Bool()
	case ArrayKind:
		return jen.Index().Add(generateTypeRef(t.Element))
	default:
		if t.Import != nil {
			return jen.Qual(t.Import.Path,title(t.Name))
		}
		return jen.Id(title(t.Name))
	}
}

// generateJSONTag generates a JSON tag for a field in a struct
func generateJSONTag(f *GoField) *jen.Statement {
	name := untitle(f.Name)
	jsTag := fmt.Sprintf("%s,omitempty", name)
	if f.Required {
		jsTag = fmt.Sprintf("%s", name)
	}
	return jen.Tag(map[string]string{"json": jsTag})
}

// selectVersion returns the version from the CRD spec that matches the given version string
func selectVersion(spec *apiextensions.CustomResourceDefinitionSpec, version string) *apiextensions.CustomResourceDefinitionVersion {
	if len(spec.Versions) == 0 {
		return nil
	}
	if version == "" {
		return &spec.Versions[0]
	}
	for _, v := range spec.Versions {
		if v.Name == version {
			return &v
		}
	}
	return nil
}

// title capitalizes the first letter of a string and returns it using Go cases library
func title(s string) string {
	if s == "" {
		return ""
	}
	return cases.Upper(language.English).String(s[0:1]) + s[1:]
}

// untitle de-capitalizes the first letter of a string and returns it using Go cases library
func untitle(s string) string {
	if s == "" {
		return ""
	}
	return cases.Lower(language.English).String(s[0:1]) + s[1:]
}

// formatComment formats a comment string to fit within a specified width,
// without splitting words.
func formatComment(comment string, maxWidth int) []string {
	if strings.Contains(comment, "\n") {
		return []string{comment}
	}

	words := strings.Fields(comment)
	var lines []string
	var currentLine string

	for _, word := range words {
		if len(currentLine)+len(word)+1 > maxWidth {
			lines = append(lines, currentLine)
			currentLine = word
		} else {
			if currentLine != "" {
				currentLine += " "
			}
			currentLine += word
		}
	}
	if currentLine != "" {
		lines = append(lines, currentLine)
	}
	return lines
}
