kind: Config
apiVersion: atlas2crd.mongodb.com/v1alpha1

spec:
  pluginSets:
    - name: atlas
      default: true
      plugins:
        - major_version
        - parameters
        - entry
        - status
        - sensitive_properties
        - skipped_properties
        - read_only_properties
        - read_write_only_properties

  openapi:
    - name: v20250312
      package: go.mongodb.org/atlas-sdk/v20250312005/admin

  crd:
    - gvk:
        version: v1
        kind: Group
        group: atlas.generated.mongodb.com
      categories:
        - atlas
      shortNames:
        - ag
      mappings:
        - majorVersion: v20250312
          openAPIRef:
            name: v20250312
          parameters:
            path:
              name: '/api/atlas/v2/groups'
              verb: post
          entry:
            schema: "Group"
            filters:
              readWriteOnly: true
          status:
            schema: "Group"
            filters:
              readOnly: true
              skipProperties:
                - $.links