apiVersion: atlas.generated.mongodb.com/v1
kind: DatabaseUser
metadata:
  name: my-databaseuser
spec:
  connectionSecretRef:
    name: mongodb-atlas-operator-api-key
  v20250312:
    groupId: "6558f184beba40022cbb2043"
    entry:
      databaseName: admin
      username: my-user
      passwordSecretRef:
        name: my-password-secret
      roles:
        - databaseName: admin
          roleName: readAnyDatabase
