apiVersion: atlas.generated.mongodb.com/v1
kind: Group
metadata:
  name: my-group
  namespace: mongodb-atlas-system
spec:
  connectionSecretRef:
    name: mongodb-atlas-operator-api-key
  v20250312:
    entry:
      orgId: "61d8221e885580463210df3d"
      name: my-group

