#!/bin/bash
# Copyright 2026 MongoDB Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Create release PR with all updated artifacts
# Usage: ./scripts/create-release-pr.sh <release_tag> <version>
# Example: ./scripts/create-release-pr.sh v2.14.0 2.14.0

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# Git bot configuration (for commits created by this script)
GIT_BOT_USER="release-bot[bot]"
GIT_BOT_EMAIL="456789+release-bot[bot]@users.noreply.github.com"

RELEASE_TAG="${1:-}"
VERSION="${2:-}"

if [ -z "${RELEASE_TAG}" ] || [ -z "${VERSION}" ]; then
    echo "Error: RELEASE_TAG and VERSION are required" >&2
    echo "Usage: $0 <release_tag> <version>" >&2
    echo "Example: $0 v2.14.0 2.14.0" >&2
    exit 1
fi

# Validate GITHUB_TOKEN or GH_TOKEN is set (prefer GH_TOKEN)
if [ -n "${GH_TOKEN:-}" ]; then
    export GITHUB_TOKEN="${GH_TOKEN}"
elif [ -z "${GITHUB_TOKEN:-}" ]; then
    echo "Error: GITHUB_TOKEN or GH_TOKEN is required" >&2
    exit 1
fi

# Configure git user via environment variables (only affects this script, not global config)
export GIT_AUTHOR_NAME="${GIT_BOT_USER}"
export GIT_AUTHOR_EMAIL="${GIT_BOT_EMAIL}"
export GIT_COMMITTER_NAME="${GIT_BOT_USER}"
export GIT_COMMITTER_EMAIL="${GIT_BOT_EMAIL}"

export BRANCH="new-release/${RELEASE_TAG}"
export COMMIT_MESSAGE="feat: release ${RELEASE_TAG}"
export RELEASE_DIR="releases/${RELEASE_TAG}"

# Create release directory (copy from released-branch)
if [ ! -d "released-branch" ]; then
    echo "Error: released-branch directory not found. Run prepare-released-branch first." >&2
    exit 1
fi

echo "Creating release directory ${RELEASE_DIR}..."
mkdir -p "${RELEASE_DIR}"
cp -rf released-branch/deploy "${RELEASE_DIR}/"
cp -rf released-branch/bundle "${RELEASE_DIR}/"
cp -rf released-branch/helm-charts "${RELEASE_DIR}/"
cp released-branch/bundle.Dockerfile "${RELEASE_DIR}/bundle.Dockerfile"
cp released-branch/licenses.csv "${RELEASE_DIR}/"
cp released-branch/docs/api-docs.md "${RELEASE_DIR}/"

# Fetch latest from origin and create/update branch
echo "Creating/updating branch ${BRANCH}..."
git fetch origin
git checkout -f -b "${BRANCH}" origin/main || git checkout -f "${BRANCH}"
git push -f origin "${BRANCH}"

# Bump version.json (in released-branch, but output to current dir)
echo "Bumping version.json..."
(cd released-branch && devbox run -- make bump-version-file)
cp released-branch/version.json .

# Update Helm Charts on main
echo "Updating Helm charts..."
cp -r "${RELEASE_DIR}/helm-charts" .

# Stage files and create signed commit
echo "Staging files and creating signed commit..."
git add -f "${RELEASE_DIR}" helm-charts version.json

export REPO_OWNER="${REPO_OWNER:-mongodb}"
export REPO_NAME="${REPO_NAME:-mongodb-atlas-kubernetes}"
export REMOTE="${REMOTE:-origin}"
"${SCRIPT_DIR}/create-signed-commit.sh"

# Check if PR already exists
echo "Checking for existing PR..."
existing_pr=$(gh pr list \
    --head "${BRANCH}" \
    --base main \
    --state open \
    --json number \
    --jq '.[0].number' 2>/dev/null || echo "")

# Create PR if it doesn't exist
if [ -z "${existing_pr}" ]; then
    echo "Creating draft PR..."
    gh pr create \
        --draft \
        --base main \
        --head "${BRANCH}" \
        --title "${COMMIT_MESSAGE}" \
        --body "This is an autogenerated PR to prepare for the release."
    echo "✓ Draft PR created"
else
    echo "PR #${existing_pr} already exists, skipping creation (branch updated)"
fi

echo "✓ Release PR step complete"

