package render

import (
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"

	"github.com/josvazg/crd2go/internal/gotype"
)

const (
	CommentMaxWidth = 80
)

const (
	metav1Package = "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type JenRenderer struct{}

func (jr JenRenderer) RenderDoc(req *gotype.Request, group, version string) error {
	if err := renderDocFile(req, group, version); err != nil && !errors.Is(err, os.ErrExist) {
		return fmt.Errorf("failed to generate doc.go file: %w", err)
	}
	return nil
}

func (jr JenRenderer) RenderSchema(req *gotype.Request, group, version string) error {
	if err := renderSchemeFile(req, group, version); err != nil && !errors.Is(err, os.ErrExist) {
		return fmt.Errorf("failed to generate schema.go file: %w", err)
	}
	return nil
}

func (jr JenRenderer) RenderCRD(req *CRDRenderRequest) error {
	f := jen.NewFile(req.Version)
	renderCRDFileHeader(f, req.Kind)

	f.Comment("+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object")
	f.Comment("+kubebuilder:object:root=true").Line()

	if err := renderGoType(f, req.TypeDict, req.Type); err != nil {
		return fmt.Errorf("failed to generate CRD type for %q: %w", req.Kind, err)
	}
	renderCRDListObject(f, req.Kind)

	overwrite := true
	w, err := req.CodeWriterFn(req.Filename, overwrite)
	if err != nil {
		return fmt.Errorf("failed to get writer for %s: %w", req.Filename, err)
	}
	defer w.Close()
	if err := f.Render(w); err != nil {
		return fmt.Errorf("failed to write Go code: %w", err)
	}
	return nil
}

func renderCRDFileHeader(f *jen.File, kind string) {
	f.HeaderComment("Code generated by crd2go. DO NOT EDIT.")
	f.ImportAlias(metav1Package, "metav1")
	f.Func().Id("init").Params().Block(
		jen.Id("SchemeBuilder").Dot("Register").Params(
			jen.Op("&").Id(kind).Values(),
		),
		jen.Id("SchemeBuilder").Dot("Register").Params(
			jen.Op("&").Id(kind+"List").Values(),
		),
	)
}

// renderType generates the spec of the CRD
func renderGoType(f *jen.File, td *gotype.TypeDict, goType *gotype.GoType) error {
	goTypeCode, err := generateType(f, td, goType)
	if err != nil {
		return fmt.Errorf("failed to generate code for %q: %w", goType.Name, err)
	}
	f.Add(goTypeCode)
	return nil
}

// renderCRDListObject generates the root object for the CRD
func renderCRDListObject(f *jen.File, kind string) {
	f.Comment("+kubebuilder:object:root=true")
	f.Type().Id(kind+"List").Struct(
		jen.Qual(metav1Package, "TypeMeta").Tag(map[string]string{"json": ",inline"}),
		jen.Qual(metav1Package, "ListMeta").Tag(map[string]string{"json": "metadata,omitempty"}),
		jen.Id("Items").Index().Id(kind).Tag(map[string]string{"json": "items"}),
	)
}

func renderDocFile(req *gotype.Request, group, version string) error {
	f := jen.NewFile(version)
	f.HeaderComment("Code generated by crd2go. DO NOT EDIT.")
	f.HeaderComment("+k8s:deepcopy-gen=package")
	f.HeaderComment(fmt.Sprintf("+groupName=%s", group))
	f.Add(jen.Commentf("controller-gen object paths=..."))
	overwrite := false
	wc, err := req.CodeWriterFn("doc.go", overwrite)
	if err != nil {
		return fmt.Errorf("failed to prepare doc.go for writting: %w", err)
	}
	if err := f.Render(wc); err != nil {
		return fmt.Errorf("failed to write Go code to doc.go: %w", err)
	}
	return nil
}

func renderSchemeFile(req *gotype.Request, group, version string) error {
	f := jen.NewFile(version)
	f.HeaderComment("Code generated by crd2go. DO NOT EDIT.")
	f.Var().Defs(
		jen.Comment("GroupVersion is group version used to register these objects"),
		jen.Id("GroupVersion").Op("=").Qual("k8s.io/apimachinery/pkg/runtime/schema", "GroupVersion").Values(
			jen.Dict{
				jen.Id("Group"):   jen.Lit(group),
				jen.Id("Version"): jen.Lit(version),
			},
		),
		jen.Line(),
		jen.Comment("SchemeBuilder is used to add go types to the GroupVersionKind scheme"),
		jen.Id("SchemeBuilder").Op("=").Op("&").Qual("sigs.k8s.io/controller-runtime/pkg/scheme", "Builder").Values(
			jen.Dict{
				jen.Id("GroupVersion"): jen.Id("GroupVersion"),
			},
		),
		jen.Line(),
		jen.Comment("AddToScheme adds the types in this group-version to the given scheme"),
		jen.Id("AddToScheme").Op("=").Id("SchemeBuilder").Dot("AddToScheme"),
	)

	overwrite := true
	wc, err := req.CodeWriterFn("scheme.go", overwrite)
	if err != nil {
		return fmt.Errorf("failed to prepare scheme.go for writting: %w", err)
	}
	if err := f.Render(wc); err != nil {
		return fmt.Errorf("failed to write Go code to scheme.go: %w", err)
	}
	return nil
}

// generateType generates Go code for a given type using the provided TypeDict
func generateType(f *jen.File, td *gotype.TypeDict, t *gotype.GoType) (*jen.Statement, error) {
	if t.Import != nil { // do not generate code for known imported types
		return jen.Null(), nil
	}
	if t.Kind == gotype.StructKind {
		return generateStructType(f, td, t)
	}
	if t.Kind == gotype.ArrayKind {
		return generateArrayType(f, td, t)
	}
	if t.Kind == gotype.MapKind {
		return generateMapType(f, td, t)
	}
	return nil, fmt.Errorf("unsupported type %q", t.Kind)
}

// generateStructType generates Go code for a struct type
func generateStructType(f *jen.File, td *gotype.TypeDict, t *gotype.GoType) (*jen.Statement, error) {
	fields := make([]jen.Code, 0, len(t.Fields))
	subtypes := make([]jen.Code, 0, len(t.Fields))
	for _, field := range t.Fields {
		fieldCode, err := generateField(f, field)
		if err != nil {
			return nil, fmt.Errorf("failed to generate field %s: %w", field.Name, err)
		}
		fields = append(fields, fieldCode)
		subtype, err := generateSubtype(f, td, field.GoType)
		if err != nil {
			return nil, fmt.Errorf("failed to generate field %s subtype: %w", field.Name, err)
		}
		subtypes = append(subtypes, subtype)
	}
	return jen.Line().Line().Type().Id(t.Name).Struct(fields...).Add(subtypes...), nil
}

// generateArrayType generates Go code for an array type
func generateArrayType(f *jen.File, td *gotype.TypeDict, t *gotype.GoType) (*jen.Statement, error) {
	elementType, err := generateSubtype(f, td, t.Element)
	if err != nil {
		return nil, fmt.Errorf("failed to generate array subtype: %w", err)
	}
	return elementType, nil
}

// generateMapType generates Go code for an array type
func generateMapType(f *jen.File, td *gotype.TypeDict, t *gotype.GoType) (*jen.Statement, error) {
	elementType, err := generateSubtype(f, td, t.Element)
	if err != nil {
		return nil, fmt.Errorf("failed to generate map subtype: %w", err)
	}
	return elementType, nil
}

// generateSubtype generates Go code for a subtype of a given type
func generateSubtype(f *jen.File, td *gotype.TypeDict, t *gotype.GoType) (*jen.Statement, error) {
	baseType := t.BaseType()
	if !baseType.IsPrimitive() && !td.WasGenerated(baseType) {
		subtypeCode, err := generateType(f, td, baseType)
		if err != nil {
			return nil, fmt.Errorf("failed to generate subtype %s: %w", t.Name, err)
		}
		td.MarkGenerated(baseType)
		return subtypeCode, nil
	}
	return jen.Null(), nil
}

// generateField generates Go code for a field in a struct
func generateField(f *jen.File, field *gotype.GoField) (jen.Code, error) {
	fieldCode := jen.Null()
	if field.Comment != "" {
		fieldCode = generateFieldComment(fieldCode, field.Name, field.Comment)
	}
	if !field.IsEmbedded() {
		fieldCode = fieldCode.Id(field.Name)
	}
	if field.GoType == nil {
		return nil, fmt.Errorf("field %q has no Go type", field.Name)
	}
	typeRefCode, err := qualifyRequired(generateTypeRef(f, field.GoType), field.Required)
	if err != nil {
		return nil, fmt.Errorf("failed to generate field type: %w", err)
	}
	return fieldCode.Add(typeRefCode).Add(generateJSONTag(field)).Line(), nil
}

// generateFieldComment generates a comment for a field in a struct
func generateFieldComment(code *jen.Statement, name, comment string) *jen.Statement {
	goComment := fmt.Sprintf("%s %s", name, comment)
	lines := formatComment(goComment, CommentMaxWidth)
	for _, line := range lines {
		code.Add(jen.Comment(line).Line())
	}
	return code
}

// qualifyRequired qualifies the type reference based on whether the field is required
func qualifyRequired(typeRef *jen.Statement, required bool) (*jen.Statement, error) {
	if required {
		return typeRef, nil
	}
	return jen.Op("*").Add(typeRef), nil
}

// generateTypeRef generates a type reference for a given GoType
func generateTypeRef(f *jen.File, t *gotype.GoType) *jen.Statement {
	switch t.Kind {
	case gotype.StringKind:
		return jen.String()
	case gotype.IntKind:
		return jen.Int()
	case gotype.FloatKind:
		return jen.Float64()
	case gotype.BoolKind:
		return jen.Bool()
	case gotype.ArrayKind:
		return jen.Index().Add(generateTypeRef(f, t.Element))
	case gotype.MapKind:
		return jen.Map(jen.String()).Add(generateTypeRef(f, t.Element))
	default:
		if t.Import != nil {
			if t.Import.Alias != "" {
				f.ImportAlias(t.Import.Path, t.Import.Alias)
			}
			return jen.Qual(t.Import.Path, title(t.Name))
		}
		return jen.Id(title(t.Name))
	}
}

// generateJSONTag generates a JSON tag for a field in a struct
func generateJSONTag(f *gotype.GoField) *jen.Statement {
	jsTag := f.CustomJSONTag
	if jsTag == "" {
		jsTag = fmt.Sprintf("%s,omitempty", f.Key)
		if f.Required {
			jsTag = fmt.Sprintf("%s", f.Key)
		}
	}
	return jen.Tag(map[string]string{"json": jsTag})
}

// formatComment formats a comment string to fit within a specified width,
// without splitting words.
func formatComment(comment string, maxWidth int) []string {
	if strings.Contains(comment, "\n") {
		return []string{comment}
	}

	words := strings.Fields(comment)
	var lines []string
	var currentLine string

	for _, word := range words {
		if len(currentLine)+len(word)+1 > maxWidth {
			lines = append(lines, currentLine)
			currentLine = word
		} else {
			if currentLine != "" {
				currentLine += " "
			}
			currentLine += word
		}
	}
	if currentLine != "" {
		lines = append(lines, currentLine)
	}
	return lines
}

// title capitalizes the first letter of a string and returns it using Go cases library
func title(s string) string {
	if s == "" {
		return ""
	}
	s = strings.TrimLeft(s, "_") // remove leading underscores
	return cases.Upper(language.English).String(s[0:1]) + s[1:]
}
