//go:build !ignore_autogenerated

//Copyright 2025 MongoDB Inc
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package project

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Integration) DeepCopyInto(out *Integration) {
	*out = *in
	out.LicenseKeyRef = in.LicenseKeyRef
	out.WriteTokenRef = in.WriteTokenRef
	out.ReadTokenRef = in.ReadTokenRef
	out.APIKeyRef = in.APIKeyRef
	out.ServiceKeyRef = in.ServiceKeyRef
	out.APITokenRef = in.APITokenRef
	out.RoutingKeyRef = in.RoutingKeyRef
	out.SecretRef = in.SecretRef
	out.PasswordRef = in.PasswordRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Integration.
func (in *Integration) DeepCopy() *Integration {
	if in == nil {
		return nil
	}
	out := new(Integration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAccessList) DeepCopyInto(out *IPAccessList) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAccessList.
func (in *IPAccessList) DeepCopy() *IPAccessList {
	if in == nil {
		return nil
	}
	out := new(IPAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	if in.WaveAssignment != nil {
		in, out := &in.WaveAssignment, &out.WaveAssignment
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionalizedPrivateEndpoint) DeepCopyInto(out *RegionalizedPrivateEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionalizedPrivateEndpoint.
func (in *RegionalizedPrivateEndpoint) DeepCopy() *RegionalizedPrivateEndpoint {
	if in == nil {
		return nil
	}
	out := new(RegionalizedPrivateEndpoint)
	in.DeepCopyInto(out)
	return out
}
