// Copyright 2025 MongoDB Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package exporter

import (
	"fmt"
	"syscall"
	"testing"

	"github.com/spf13/afero"
	"github.com/stretchr/testify/require"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
)

func TestSingleFileOpen(t *testing.T) {
	tests := map[string]struct {
		fs            afero.Fs
		filename      string
		overwrite     bool
		preCreateFile bool
		expectedError error
	}{
		"creates file when it does not exist": {
			fs:       afero.NewMemMapFs(),
			filename: "testdata/output.yaml",
		},
		"creates parent directories when they do not exist": {
			fs:       afero.NewMemMapFs(),
			filename: "testdata/nested/deep/output.yaml",
		},
		"fails if file exists and overwrite is false": {
			fs:            afero.NewMemMapFs(),
			filename:      "testdata/groups.atlas.generated.mongodb.com.yaml",
			overwrite:     false,
			preCreateFile: true,
			expectedError: fmt.Errorf("file %s already exists, use --force to overwrite", "testdata/groups.atlas.generated.mongodb.com.yaml"),
		},
		"overwrites file if it exists and overwrite is true": {
			fs:            afero.NewMemMapFs(),
			filename:      "testdata/groups.atlas.generated.mongodb.com.yaml",
			overwrite:     true,
			preCreateFile: true,
		},
		"fails when directory cannot be created": {
			fs:            afero.NewReadOnlyFs(afero.NewMemMapFs()),
			filename:      "nonexistent/dir/output.yaml",
			expectedError: fmt.Errorf("failed to create directory for file %s: %w", "nonexistent/dir/output.yaml", syscall.EPERM),
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			if tt.preCreateFile {
				_, err := tt.fs.Create(tt.filename)
				require.NoError(t, err)
			}

			exp := NewSingleFileExporter(tt.fs, tt.filename, tt.overwrite)

			err := exp.Open()
			require.Equal(t, tt.expectedError, err)

			if err == nil {
				info, statErr := tt.fs.Stat(tt.filename)
				require.NoError(t, statErr)
				require.False(t, info.IsDir())
			}
		})
	}
}

//func TestSingleFileOpenWritesHeader(t *testing.T) {
//	fs := afero.NewMemMapFs()
//	exp := NewSingleFileExporter(fs, "testdata/output.yaml", false)
//
//	require.NoError(t, exp.Open())
//	require.NoError(t, exp.Close())
//
//	data, err := afero.ReadFile(fs, "testdata/output.yaml")
//	require.NoError(t, err)
//	require.Equal(t, "# The file is generated by openapi2crd\n", string(data))
//}

//func TestSingleFileOpenFailsWhenFileCannotBeOpened(t *testing.T) {
//	base := afero.NewMemMapFs()
//	require.NoError(t, base.MkdirAll("testdata", 0o755))
//
//	fs := &openFileFailFs{Fs: base}
//	exp := NewSingleFileExporter(fs, "testdata/output.yaml", false)
//
//	err := exp.Open()
//	require.Error(t, err)
//	assert.Contains(t, err.Error(), "failed to open file")
//}

func TestSingleFileExport(t *testing.T) {
	tests := map[string]struct {
		filename      string
		overwrite     bool
		crd           *apiextensionsv1.CustomResourceDefinition
		yaml          string
		expectedError error
	}{
		"export to file": {
			filename:  "testdata/groups.atlas.generated.mongodb.com.yaml",
			overwrite: true,
			crd:       sampleCRD(),
			yaml:      "# The file is generated by openapi2crd\n---\n" + expectedCRDBody,
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			fs := afero.NewMemMapFs()
			_, err := fs.Create(tt.filename)
			require.NoError(t, err)

			exp := NewSingleFileExporter(fs, tt.filename, tt.overwrite)

			err = exp.Open()
			require.NoError(t, err)

			err = exp.Export(tt.crd)
			require.Equal(t, tt.expectedError, err)
			data, err := afero.ReadFile(fs, tt.filename)
			require.NoError(t, err)
			require.Equal(t, tt.yaml, string(data))

			err = exp.Close()
			require.NoError(t, err)
		})
	}
}
