// Copyright 2025 MongoDB Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package exporter

import (
	"fmt"
	"path/filepath"

	"github.com/pkg/errors"
	"github.com/spf13/afero"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
)

// SingleFileExporter writes all CRDs into a single YAML file separated by "---".
type SingleFileExporter struct {
	fs        afero.Fs
	filename  string
	overwrite bool
	file      afero.File
}

func NewSingleFileExporter(fs afero.Fs, filename string, overwrite bool) *SingleFileExporter {
	return &SingleFileExporter{
		fs:        fs,
		filename:  filename,
		overwrite: overwrite,
	}
}

func (e *SingleFileExporter) Open() error {
	exists, err := afero.Exists(e.fs, e.filename)
	if err != nil {
		return fmt.Errorf("failed to check if file exists: %w", err)
	}

	if exists && !e.overwrite {
		return fmt.Errorf("file %s already exists, use --force to overwrite", e.filename)
	}

	if err = e.fs.MkdirAll(filepath.Dir(e.filename), defaultDirectoryPermission); err != nil {
		return fmt.Errorf("failed to create directory for file %s: %w", e.filename, err)
	}

	e.file, err = e.fs.OpenFile(e.filename, createOrUpdate, defaultFilePermission)
	if err != nil {
		return fmt.Errorf("failed to open file %s: %w", e.filename, err)
	}

	_, err = e.file.WriteString("# The file is generated by openapi2crd\n")
	if err != nil {
		return fmt.Errorf("failed to write the header to file %s: %w", e.filename, err)
	}

	return nil
}

func (e *SingleFileExporter) Export(crd *apiextensions.CustomResourceDefinition) error {
	yamlBytes, err := marshalCrd(crd)
	if err != nil {
		return errors.New("Failed to marshall CRD when writing output")
	}

	_, err = e.file.WriteString("---\n")
	if err != nil {
		return fmt.Errorf("failed to write the separator to file %s: %w", e.filename, err)
	}
	_, err = e.file.Write(yamlBytes)
	if err != nil {
		return fmt.Errorf("failed to write the content to file %s: %w", e.filename, err)
	}

	return nil
}

func (e *SingleFileExporter) Close() error {
	if e.file != nil {
		return e.file.Close()
	}

	return nil
}
