name: Clean tool CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/clean/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tools/clean/**'

permissions:
  contents: read

jobs:

  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'

    - name: CI checks
      env:
        GOTOOLCHAIN: auto
      working-directory: ./tools/clean
      run: go build ./... && go test ./...
