name: Send SBOMs to Kondukto

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the operator to send SBOMs for"
        required: true
        type: string

permissions:
  contents: read

jobs:
  send-sboms:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.15.0
      with:
        enable-cache: 'true'

    - name: Configure AWS credentials for DevProd Platforms ECR
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.DEVPROD_PLATFORMS_ECR_ROLE_ARN }}
        aws-region: us-east-1

    - name: Log in to DevProd Platforms ECR
      uses: docker/login-action@v4
      with:
        registry: 901841024863.dkr.ecr.us-east-1.amazonaws.com

    - name: Send SBOMs to Kondukto
      env:
        VERSION: ${{ github.event.inputs.version }}
        KONDUKTO_TOKEN: ${{ secrets.KONDUKTO_TOKEN }}
      run: |
        devbox run -- make send-sboms

